### ISSUE TITLE
Slow Load leads to white screen 

### ISSUE THREAD

**Issue by Ryex** [Antergos/lightdm-webkit2-greeter#1]
this version loads at least 15 seconds slower than lightdm-webkit-greeter and as a result there is a white screen that appears while webkit prepares to render the chosen.

I'm unsure of what should be done to smooth out the transition.

while of no great importance it is a bit ugly.

of topic abit, I love this. I was constantly fighting small bugs with the previous webkit version. now this white screen before it loads is the only annoyance!

**Comment by WokSearedBacon** [comment]
Same with me, If find it too odd having the sudden FLASH go off when I would expect to just see the login menu. I'll see what I can find.

**Comment by Luke-Nukem** [comment]
This seems to be caused by animations in themes. Try turning animation delays down to 0.1 or so.

It would be nice, however, to have the blank fill default to black instead of white. It's quite blinding at night.
