### ISSUE TITLE
Blank screen when trying to login after upgrade to gnome-shell 3.18

### ISSUE THREAD

**Issue by synaptiko** [Antergos/lightdm-webkit2-greeter#10]
Hi,

I've recently upgraded to gnome-shell 3.18 and following started to happen to me:
1. login screen with clock is shown
2. click on clock or press enter
3. user list appears but after while screen go completely white

If I use enter I can at least type my password and log into my session.

I found following in /var/log/lightdm/x-1-greeter.log:
(lightdm-webkit2-greeter:1885): Gtk-WARNING **: drawing failure for widget 'WebKitWebView': invalid value for an input Visual*
(lightdm-webkit2-greeter:1885): Gtk-WARNING **: drawing failure for widget 'GtkWindow': invalid value for an input Visual*
(WebKitWebProcess:1919): Gdk-WARNING **: WebKitWebProcess: Fatal IO error 0 (Success) on X server :1.

If you need some additional info I can provide it.
Thanks

**Comment by Wabuo** [comment]
Same her. I can still log in if I use enter to focus the “clock” the screen turns gray and i have to insert my password blindly, but if I use a mouse click I'm lost and i have to reboot over the console(alt+Fx).

**Comment by melkir** [comment]
Same here :+1:

**Comment by honorabrutroll** [comment]
Same problem here.

**Comment by ajoberstar** [comment]
Same here

**Comment by niccolatorres** [comment]
same here

**Comment by lots0logs** [comment]
@everyone, this bug has been confirmed. Please do not post any more "me too" comments. We are working on the issue and will notify everyone once it has been solved. Thanks!

**Comment by Commod0re** [comment]
I've found a fix for this. Are you accepting pull requests?

**Comment by karasu** [comment]
Of course!!!

El dimarts, 13 d’octubre de 2015, Michael Greene <notifications@github.com>
va escriure:

> I've found a fix for this. Are you accepting pull requests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/lightdm-webkit2-greeter/issues/10#issuecomment-147797136>
> .
>


-- 
Enviat amb el meu Iphone

**Comment by Commod0re** [comment]
It looks like it was already fixed in 476b189e2e2f5dc099309e0ad0b7d932619cfcad, actually. The fix I found was changing `gdk_cursor_new` to `gdk_cursor_new_for_display`.

**Comment by samchi70** [comment]
Its still not fixed.

**Comment by Commod0re** [comment]
that new release did not end up fixing it for me, either, which seems odd to me, but I did one other thing slightly differently. I will test that other change against the current version and see if that solves it

**Comment by Commod0re** [comment]
yeah I guess it was the other thing, too. Pull request submitted; that change fixes it for me.

**Comment by samchi70** [comment]
That last commit fixed it, Thank you!.  Now I was wondering how is it possible to make the background span instead of zoom?

**Comment by opensusecatala** [comment]
Thanks a lot for the fix. Good job!

**Comment by opensusecatala** [comment]
Thanks a lot for the fix. Good job!

**Comment by opensusecatala** [comment]
Thanks a lot for the fix. Good job!

**Comment by Davidmp1** [comment]
Thanks a lot for the fix. Good job!

**Comment by synaptiko** [comment]
It also works for me now. Thank you!
