### ISSUE TITLE
Enabling clamd causes various login screen issues

### ISSUE THREAD

**Issue by philwyettreb** [Antergos/lightdm-webkit2-greeter#101]
Enabling clamd causes various login screen issues.

$ sudo systemctl enable clamd.service

Issues:

- Chosen image is replaced by another and image list only has 'random' entry in it.
- Entering login. Icon next to username is missing.

**Comment by philwyettreb** [comment]
To better show this issue.

Before enabling clamd.

![screenshot from 2016-12-30 12-57-02](https://cloud.githubusercontent.com/assets/24805379/21565445/e3531c84-ce8f-11e6-894f-19a360373002.png)
![screenshot from 2016-12-30 12-57-15](https://cloud.githubusercontent.com/assets/24805379/21565446/e3575d76-ce8f-11e6-8d28-c046e0dba5d2.png)

After enabling clamd and rebooting.

![screenshot from 2016-12-30 12-58-33](https://cloud.githubusercontent.com/assets/24805379/21565451/fda66816-ce8f-11e6-867f-dad1bd8dd781.png)
![screenshot from 2016-12-30 12-58-38](https://cloud.githubusercontent.com/assets/24805379/21565452/fdaab290-ce8f-11e6-9dc3-565972ba3b7e.png)
![screenshot from 2016-12-30 12-58-45](https://cloud.githubusercontent.com/assets/24805379/21565453/fdaf27e4-ce8f-11e6-8903-365ce16aa2df.png)

**Comment by lots0logs** [comment]
@philwyettreb I'm not sure what exactly are the issues? I can see that no background images are showing in the background switcher. Other than that I dont see any issues in your screenshots. Also I honestly cant think of any way that clamd could have an effect on the greeter. (Of course that doesnt mean there aren't any).

**Comment by philwyettreb** [comment]
The graphical issues caused are from various causes as I have come to find. One being clamav, if not configured a certain way. Others involve sysctl tweaking of parameters.

I will close this for now and come back too it after some further work and documenting of the results.
