### ISSUE TITLE
Default theme not working

### ISSUE THREAD

**Issue by Kaspichhh** [Antergos/lightdm-webkit2-greeter#106]
I'm having some problems with greeter, the default theme is showing, but when I click on password input, the who desktop turns black and only cursor is showing. The same issue is showing up when I use my own theme, but this time it wont even load, and just shows black screen. Only theme which is working is lightdm-webkit-material.
[Untitled.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/689796/Untitled.txt)

**Comment by lots0logs** [comment]
Hi, could you provide the contents of `/var/log/lightdm/seat0-greeter.log` immediately after the issue occurs? You will have to switch to an alternate VT and create a copy of the file somewhere otherwise it will be overwritten when you log in to your session.

**Comment by Kaspichhh** [comment]
Sorry, that it took so long time to answer.
[seat0-greeter.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/702190/seat0-greeter.txt)

**Comment by nikoTM** [comment]
Can confirm, but I only get

```
** (lightdm-webkit2-greeter:327) WARNING **: Error running javascript: An exception was raised in JavaScript
```

**Comment by lots0logs** [comment]
@Kaspichhh Could you post the contents of `/etc/lightdm/lightdm-webkit2-greeter.conf`?

**Comment by Kaspichhh** [comment]
At that time I had my own theme set as default, and right now none of themes are working. 

#
# [greeter]
# debug_mode          = Greeter theme debug mode.
# detect_theme_errors = Provide an option to load a fallback theme when theme errors are detected.
# screensaver_timeout = Blank the screen after this many seconds of inactivity.
# secure_mode         = Don't allow themes to make remote http requests.
# time_format         = A moment.js format string so the greeter can generate localized time for display.
# time_language       = Language to use when displaying the time or "auto" to use the system's language.
# webkit_theme        = Webkit theme to use.
#
# NOTE: See moment.js documentation for format string options: http://momentjs.com/docs/#/displaying/format/
#

[greeter]
debug_mode          = true
detect_theme_errors = true
screensaver_timeout = 300
secure_mode         = true
time_format         = LT
time_language       = auto
webkit_theme        = neckos-webkit

#
# [branding]
# background_images = Path to directory that contains background images for use by themes.
# logo              = Path to logo image for use by greeter themes.
# user_image        = Default user image/avatar. This is used by themes for users that have no .face image.
#
# NOTE: Paths must be accessible to the lightdm system user account (so they cannot be anywhere in /home)
#

[branding]
background_images = /usr/share/backgrounds
logo              = /usr/share/lightdm-webkit/themes/antergos/img/antergos.png
user_image        = /usr/share/lightdm-webkit/themes/antergos/img/antergos-logo-user.png

**Comment by lots0logs** [comment]
Your logs indicate that there is a problem with the greeter config file. How did you install the greeter? Did you use the package from our OBS repo?

**Comment by Kaspichhh** [comment]
Yes, I used OBS repo.

**Comment by lots0logs** [comment]
Hmm..I'll have to install Ubuntu on a VM and see if I can identify the problem. I'll do that as soon as I can and let you know how it goes.

**Comment by Kaspichhh** [comment]
Weird thing is that I have installed this greeter on several pc's and only on two I got this bug. And usually its working ok at beginning, but when pc had been shut down for while, this bug appears.

**Comment by Kaspichhh** [comment]
Is there any progress?

**Comment by Kaspichhh** [comment]
New update resolved my problem too, so I guess it was the same as in #107
