### ISSUE TITLE
Log In screen only shows black screen with mouse pointer after updates

### ISSUE THREAD

**Issue by DanteIgashu** [Antergos/lightdm-webkit2-greeter#107]
Updates applied on Tuesday January 17, 2017.

Issue seems to be similar to https://github.com/Antergos/lightdm-webkit2-greeter/issues/106
I am not sure if the update was the problem, before this happened I used to get the same error mentioned on this other issue https://github.com/Antergos/lightdm-webkit2-greeter/issues/105 but I could log in with no problems even without taking any of the options shown on the error window (the log in screen looked just fine).

I didn't notice the issue until I locked my session, after coming back and getting an image on my monitor (laptop monitor) it didn't show anything else but what mentioned before.
I would like to know if this can be solved with a simple update, or do I have to do something else in order to solve the issue?
Can I help in some way?
Does anyone know if I can run gnome after login in using ctrl + alt +F2?

THANKS IN ADVANCE! : )

**Comment by furufuru** [comment]
I got same issue. webkit2gtk(2.14.3-1) seem to be a problem.
Downgrade to 2.14.2-2. That works for me.

**Comment by duncanyoyo1** [comment]
I also had the same issue, I was running the lightdm-webkit2-greeter-next and when webkit2gtk updated it caused the same issue. I downgraded to 2.14.2-2 and everything is working normally again.

**Comment by TomasDuda** [comment]
Same problem.

Temporary solution:

- install `lightdm-gtk-greeter`
- change `greeter-session` in /etc/lightdm/lightdm.conf
- restart the lightdm service

**Comment by WildAndrewLee** [comment]
I'm getting the same error. Using lightdm-gtk-greeter for now.

Contents of `/var/log/lightdm/seat0-greeter.log`
```
** (lightdm-webkit2-greeter:546): WARNING **: Error running javascript: An exception was raised in JavaScript
  3 Gdk-Message: lightdm-webkit2-greeter: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

**Comment by JakobEriksson** [comment]
Reverting back to webkit2gtk 2.14.2.2 also works for a temp sollution.

**Comment by roytenberg** [comment]
Just got hit with the update, and everything is broken. Jumped to tty2 with ctrl + alt + F2, and disabled and stopped lightdm in favor of gdm. I'll try again in a week.
