### ISSUE TITLE
Rename package to avoid confusion with deprecated and insecure webkit2

### ISSUE THREAD

**Issue by philwyettreb** [Antergos/lightdm-webkit2-greeter#112]
I would put forward to rename package to avoid confusion with deprecated and insecure webkit2.

Possibles:

* lightdm-webkitgtk-greeter
* lightdm-antergos-greeter

**Insert suggestions at bottom of list**

**Comment by lots0logs** [comment]
I'm currently rewriting the greeter to use QtWebEngine. I'm planning to change the name of the package to `web-greeter` once the rewrite is complete :smiley:

**Comment by philwyettreb** [comment]
Ah... Good job I use 'gdm-plymouth'. I have this thing of using GNOME and having no QT/KDE at all on my systems. That also stretches to no 'lib32-anything' ;-)

**Comment by lots0logs** [comment]
Sorry to say I dont really see the point in that. Qt has become a modular platform so its not like it used to be (where you had to install almost all of KDE when you installed Qt)

**Comment by philwyettreb** [comment]
I am of the old school of I don't need masses of packages from here and there to make a system. I know what I want to do and if gnome/gtk does not provide it, I will code it. I come from old Red Hat and RHEL and I have some old man traits for lean systems - no mix and match. ;-)

**Comment by lots0logs** [comment]
Yeah I can respect that. I don't think it is very sensible to my own workflow, but if you like it then that's really all that matters :+1:
