### ISSUE TITLE
autogen seems okay, make fails

### ISSUE THREAD

**Issue by sabian2008** [Antergos/lightdm-webkit2-greeter#13]
Hello!
I'm trying to use antergos greeter's theme in Debian testing, so I tried manually building webkit2 greeter.
I followed the same steps I'd used for webkit-greeter, but adding the gtk3+ libraries. The result is as follows:

\# ./autogen.sh seems okay:
http://paste.debian.net/319572/

however 
\# make, fails:
http://paste.debian.net/319573/

Any idea what am I missing?

Cheers,

**Comment by lots0logs** [comment]
Are you using the latest master? I havent published a release for it yet but it is (finally) working again! :triumph:

**Comment by sabian2008** [comment]
Hey, thanks for the quick reply!

I re-downloaded the repo (master branch) with the "download as zip" link provided by github. This time, things broke earlier, while running autogen.sh:
http://paste.debian.net/320469/

**Comment by lots0logs** [comment]
@sabian2008 I added some instructions to the repo's README file. The theme is developed in a separate repo which is included in this repo as a git submodule (so there are a couple extra steps necessary to get a successful build). Let me know if you have any questions. Cheers!

**Comment by sabian2008** [comment]
Done!

Sorry if you had added it yesterday. I didn't see it.
Those instructions worked for me. I think you have an error in the line before autogen, shouldn't you cd just one directory up?

I have it working. Finally one webkit greeter that keeps last-session information. The backgrounds are broken, but I think I can handle it.

Thanks for your help. Great greeter!!

Cheers!

**Comment by lots0logs** [comment]
Yep, you are correct. I fixed it. I also added the link to our wallpapers package. In the future I'll make the wallpapers directory a build time option that can be set to any directory :smile: Cheers!
