### ISSUE TITLE
Black Rectangle 

### ISSUE THREAD

**Issue by ddulic** [Antergos/lightdm-webkit2-greeter#14]
A black rectangle maybe 300px wide and 150px high appears after entering in the the password.

**Comment by lots0logs** [comment]
Which graphics drivers are you using? Nvidia?

**Comment by ddulic** [comment]
Hardware: Lenovo y50-70 laptop with i7 and 860m 

lspci | grep VGA:
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

**Comment by FallingSnow** [comment]
I have the exact same issue. It happens about 2/3 times.
```
$ sudo lshw -c video
  *-display:0             
       description: VGA compatible controller
       product: Mobile GM965/GL960 Integrated Graphics Controller (primary)
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 0c
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:28 memory:e4400000-e44fffff memory:d0000000-dfffffff ioport:4000(size=8)
```

**Comment by archshift** [comment]
I have the same issue. For whatever reason, it becomes a lot worse when using http://github.com/artur9010/lightdm-webkit-material as a greeter.

**Comment by bendovercz** [comment]
Same issue here with Intel Graphics. And also a lot worse with [lightdm-webkit-material](https://github.com/artur9010/lightdm-webkit-material) as @archshift

**Comment by artur9010** [comment]
Same issue with nvidia graphics. GTX 550 Ti with latest nvidia proprietary driver from Arch Linux repository.

**Comment by lots0logs** [comment]
I'm fairly certain this issue is a bug in  webkit2gtk. I don't have time to report it upstream at the moment, so please feel free to do so if any of you can do it :smile:

**Comment by SalahAdDin** [comment]
Yes, there is, in left top corner, but for me, is small, sometimes tak emiddle screen.

**Comment by davze** [comment]
There seem to be upstream fixes in the webkit unstable branch adressing UI flickering.
http://webkitgtk.org/2016/03/01/webkitgtk2.11.91-released.html

**Comment by lots0logs** [comment]
Is anyone still experiencing this issue? Please let me know. Thanks!

**Comment by davze** [comment]
Issue seems to be resolved.

**Comment by FallingSnow** [comment]
Same.

**Comment by chengyi** [comment]
@lots0logs I am experiencing the bug using webkit2gtk 2.14.5-1 in ArchLinux
