### ISSUE TITLE
24h time howto

### ISSUE THREAD

**Issue by gabrielfsousa** [Antergos/lightdm-webkit2-greeter#181]
how i change the time to 24 ?

**Comment by marcsello** [comment]
I'm pretty sure this depends on the theme you choose.

EDIT:
If you looking for help for the default theme, I suggest you look around in the default theme files.
Especially around this function:
https://doclets.io/Antergos/web-greeter/stable#dl-LightDM-ThemeUtils-get_current_localized_time

**Comment by marcsello** [comment]
Okay, there is a line in the config file (somehow I missed it sry):
```
time_language       = auto
```

According to the comments above, and moment.js' documentation, you can just change this to a locale that uses 24 hour time format, like "hu" or something.
