### ISSUE TITLE
Background not respecting settings?

### ISSUE THREAD

**Issue by polarathene** [Antergos/lightdm-webkit2-greeter#20]
Have Gnome installed. applied a background to the desktop just fine. Set one for the lock screen, locked the system  Super+L, background is incorrect. Logged in, locked again, background is not the same but still incorrect, appears to be using a random background each time?

**Comment by lots0logs** [comment]
Hi, The background for the lock screen cannot be controlled from within GNOME System Settings unless you switch from LightDM to GDM. With LightDM the background can be changed from the lockscreen itself (provided the theme you are using supports it)

**Comment by polarathene** [comment]
Ah that makes sense, as a new user to linux as a desktop OS that wasn't apparent to me. Thanks for clearing up the confusion.

**Comment by lots0logs** [comment]
No worries! Ideally we would make it a bit more obvious to the user (we are discussing how we might best accomplish that sooner rather than later)
