### ISSUE TITLE
Rendering glitch on password error

### ISSUE THREAD

**Issue by polarathene** [Antergos/lightdm-webkit2-greeter#21]
If I type the password incorrectly, I get a small red box with a white `v` icon, if there was meant to be associated text to indicate an incorrect password it is missing. I am able to repeat this error, but only the first time when I lock the screen. Additional times shows no error visual at all, just appears unresponsive until I've put in the correct password.

**Comment by sbalneav** [comment]
Which theme are you using?

**Comment by polarathene** [comment]
Whatever was the default with the latest iso and Gnome installation. Still fairly new to linux as my desktop OS. Haven't looked into what driver I have installed, I don't appear to have nvidia settings in the app list so it could be due to nouveau which doesn't fully support my 860M(NV110 family).

**Comment by lots0logs** [comment]
Hi, what is your system locale setting?

**Comment by polarathene** [comment]
English (New Zealand) if that's what you meant? I could double check if you point out where to look.

**Comment by lots0logs** [comment]
No need to worry about that, I have confirmed the issue on my system. Thanks for reporting it!
