### ISSUE TITLE
Current version does not compile due to missing method declaration

### ISSUE THREAD

**Issue by vlow** [Antergos/lightdm-webkit2-greeter#22]
The current version fails to compile due to a missing declaration of get_iconsdir_cb. I tried the previous commits and it looks like the trouble started with f79e466.

**Comment by lots0logs** [comment]
Sorry I havent had a chance to update the readme. Master is no longer guaranteed to be in an unbroken state as its where we do active development. You should use the latest release tag instead. Let me know if you still have trouble.

**Comment by sbalneav** [comment]
Fixed, made pull request

**Comment by vlow** [comment]
Thanks for the info. I installed the package through the AUR (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lightdm-webkit2-greeter). Unfortunately, this package still seems to just clone the master. I will try to contact the maintainer. Just out of curiosity: why don't you develop on another branch (or even feature-branches) and use the master for stable snapshots?

**Comment by lots0logs** [comment]
> I will try to contact the maintainer.

That would be me, my bad :sweat_smile:  Its fixed now. Cheers!
