### ISSUE TITLE
Themes API :: Make a list of background images (filepaths) available to themes via config object 

### ISSUE THREAD

**Issue by lots0logs** [Antergos/lightdm-webkit2-greeter#26]
### The Problem:
We need to make it easy for the greeter to be branded by the distributions so we need to drop the dependency on `antergos-wallpapers`. 

### The Plan:
We'll allow a directory to be configured in  `lightdm-webkit2-greeter.conf` for background images. If configured, we will make a list of images (filepaths) found in the directory available to the themes via the `config` object.

### Additional Notes:
@sbalneav I could really use your help on this if you have the time :grimacing:

**Comment by sbalneav** [comment]
So... I'm assuming what we want is some kind of "directory" object, so that
we could do:

directory.dirlist("path")

and we'd receive back a javascript array of filenames that then the grreter
could do whatever it wants with?

**Comment by lots0logs** [comment]
Yes, exactly!

**Comment by sbalneav** [comment]
Are all the wallpapers in one directory, or are you expecting a recursuve listing?

**Comment by lots0logs** [comment]
I'd think one directory should be sufficient. What do you think?

**Comment by sbalneav** [comment]
Good enough for a start.  I'll code it tomorrow.

**Comment by lots0logs** [comment]
Cool. Sounds good. Thanks!!

**Comment by sbalneav** [comment]
Have a look at the latest commit in my branch; I think it does what you want.  Also, see 

https://github.com/sbalneav/lightdm-webkit2-greeter/commit/1ea83d175f2db74609abcd7f2f110ec4f011365a

Which fixes a serious bug in message handling.

**Comment by sbalneav** [comment]
Saw the typos, sorry, I tested it on lightdm-webkit-greeter, which is easier for me to develop on seeing as how jessie doesn't have new enough webkit2 libraries yet.  Does that do what you want?  Anything else?

**Comment by lots0logs** [comment]
@sbalneav No worries! It works perfectly :+1:  Thanks!! Once I get the theme cleaned up we can do a pre-release. What do you think?

**Comment by sbalneav** [comment]
Yeah, there's been enough changes in both to do a 2.1 release, i figure.

**Comment by lots0logs** [comment]
Oh and btw, I've been trying to build debian packages for the builder on OBS for the last month. The reason its taking so long is because I have to build webkitgtk from source since its not in OBS for Ubuntu/Debian and the build always gets pushed aside for official opensuse packages that need to be built. You can monitor it here:

https://build.opensuse.org/project/show/home:antergos
