### ISSUE TITLE
LightDMUser :: get_user_image_cb() :: Only pass value to themes if file exists and is accessible 

### ISSUE THREAD

**Issue by lots0logs** [Antergos/lightdm-webkit2-greeter#27]

**Comment by sbalneav** [comment]
http://people.ubuntu.com/~robert-ancell/lightdm/reference/lightdm-gobject-1-User-Accounts.html#lightdm-user-get-image

We're basically just providing the result of the lightdm callback, so it should already be that way.  Are you seeing something different?

**Comment by lots0logs** [comment]
This might actually be a bug in lightdm, I am not sure yet. While testing the theme yesterday I noticed that lightdm was providing a user image filepath that didn't actually exist: `/home/antergos/.face` I know that's the default place it looks for the image but there was no image for my test (which was a fresh installation in a VM). If I see the issue again I will report it upstream, but I figure it doesnt hurt to have a check on our end in the meantime.

**Comment by sbalneav** [comment]
My fix works for me, but now you'll have to fix the antergos theme; at one point, you do a .length, and it complains when it's NULL.

**Comment by sbalneav** [comment]
Also, check out my newer commits.  The text we receive out of lightdm via the show_message() callback is just plain text; it's got newlines, &'s potentially <'s and >'s depending on what messages any particular pam module author decides to spit at us.  To make the theme author's work a bit easier, I've added a greeterutil.txt2html() function which will clean up passed text.  Saves the author having to manually make it html "clean" in javascript.

**Comment by lots0logs** [comment]
Fixed in 64f4839fa88ca6cd93010c3b4908062fad3ba34e
