### ISSUE TITLE
Flexbox layouts don't seem to work

### ISSUE THREAD

**Issue by FallingSnow** [Antergos/lightdm-webkit2-greeter#29]
Using any kind of flex display options doesn't appear to work. Any chance flex support will be added?

**Comment by lots0logs** [comment]
Which version of webkit2gtk are you using?

**Comment by FallingSnow** [comment]
webkit2gtk-2.10.9-1

**Comment by FallingSnow** [comment]
And I can't install the latest version in the test repo because
```
lightdm-webkit2-greeter: installing webkit2gtk (2.12.0-1) breaks dependency 'webkit2gtk<2.12'
```

**Comment by lots0logs** [comment]
Flexbox works fine with the 2.10 series. Are you sure you are using it correctly. Do you have Epiphany installed? Does it work there?

**Comment by lots0logs** [comment]
You'll need to force the upgrade to webkit2gtk 3.12 (if you have gnome 3.20 packages installed).. `pacman -Sdd webkit2gtk`

**Comment by FallingSnow** [comment]
I don't know what fixed it but it's working now. I think it had to do with upgrading webkit2gtk then downgrading it again. Thanks for your support.

I have another issue though, an img with src="/home/user/.face" doesn't show the image. Only a small box with a question mark.

**Comment by lots0logs** [comment]
You can't access files in user home directories. You can get the path to the user's face image from the greeter's Javascript API. You can use the default theme as a reference. Here's the part of the code that handles adding users to the page: https://github.com/Antergos/lightdm-webkit2-greeter/blob/master/themes/antergos/js/greeter.js#L437

**Comment by FallingSnow** [comment]
I think that's what I'm already doing and it gives me a path to /home/user/.face. If the user defines a face image outside of their home in a publicly accessible directory I will then be able to display their image?

**Comment by lots0logs** [comment]
I updated the details on where and how user icons should be stored: https://github.com/Antergos/lightdm-webkit2-greeter/tree/master/themes/antergos#user-icons-management

**Comment by FallingSnow** [comment]
Thank you!

If you want to see what your efforts helped me accomplish, give this theme a whirl, https://github.com/FallingSnow/lightdm-webkit-material. I'll be submitting a pull request tonight or tomorrow.
