### ISSUE TITLE
No available users on login screen after update

### ISSUE THREAD

**Issue by fernandomayer** [Antergos/lightdm-webkit2-greeter#32]
Hi,

after the last update, which had some discussion [here](https://github.com/Antergos/antergos-packages/issues/94), I get the login screen but it doesn't appear the clock, and even when I hit Enter, no user names appear. So I'am unable to login now.

The content of `var/log/lightdm/x-0-greeter.log` is just this:

```
undefined: CONSOLE ERROR Key file does not have group 'branding'
```

Any help would be appreciated.
Thanks.

**Comment by lots0logs** [comment]
Thanks for the log output. It made the problem instantly clear to me. I'll push out an update to handle the problem. If you don't want to wait you can resolve it yourself by updating `/etc/lightdm/lightdm-webkit2-greeter.conf` with the new fields added by the latest version (the fields can be found in `/etc/lightdm/lightdm-webkit2-greeter.conf.pacnew`)

**Comment by fernandomayer** [comment]
Thanks!

Copying the `.pacnew` file solved the problem.
