### ISSUE TITLE
Using localstorage

### ISSUE THREAD

**Issue by FallingSnow** [Antergos/lightdm-webkit2-greeter#38]
The latest update has disabled localstorage resulting in [DOM exception 18](https://github.com/angular-translate/angular-translate/issues/629). I believe this is because files are loaded with the file:// protocol. I can't find any other way of storing settings.

**Comment by lots0logs** [comment]
It was an unintended side affect of a fix in upstream webkit. I have a patch for it submitted already. You can track its progress here:

https://bugs.webkit.org/show_bug.cgi?id=156651

You can see what I implemented as a temporary work around here:

https://github.com/Antergos/lightdm-webkit2-greeter/blob/master/themes/antergos/js/greeter.js#L81
https://github.com/Antergos/lightdm-webkit2-greeter/blob/master/themes/antergos/js/greeter.js#L139
https://github.com/Antergos/lightdm-webkit2-greeter/blob/master/themes/antergos/js/greeter.js#L170

Cheers!

**Comment by FallingSnow** [comment]
Thanks for the update. Unfortunately my cookie implementation works in chrome but not in lightdm. If you've got spare time my implementation is [here](https://github.com/FallingSnow/lightdm-webkit-material/blob/master/assets/bower_components/ngstorage/ngStorage.js#L137) and [here](https://github.com/FallingSnow/lightdm-webkit-material/blob/master/assets/bower_components/ngstorage/ngStorage.js#L158). Otherwise I think I'll just wait till webkit2gtk magically fixes itself :neutral_face:.

**Comment by lots0logs** [comment]
Fixed in webkit2gtk 2.12.2
