### ISSUE TITLE
Issue installing on Arch

### ISSUE THREAD

**Issue by veggiedefender** [Antergos/lightdm-webkit2-greeter#41]
I'm installing it from the AUR and here's the error I get:

    loading packages...
    resolving dependencies...
    looking for conflicting packages...
    
    Packages (1) lightdm-webkit2-greeter-2.1.4-1

    Total Installed Size:  1.61 MiB
    
    :: Proceed with installation? [Y/n] Y
    (1/1) checking keys in keyring                     [######################] 100%
    (1/1) checking package integrity                   [######################] 100%
    (1/1) loading package files                        [######################] 100%
    (1/1) checking for file conflicts                  [######################] 100%
    (1/1) checking available disk space                [######################] 100%
    :: Processing package changes...
    (1/1) installing lightdm-webkit2-greeter           [######################] 100%
    /usr/bin/bash: post_install: command not found
    error: command failed to execute correctly

**Comment by lots0logs** [comment]
I think this is a regression bug in pacman. Its trying to call install scripts when they are commented out. Anyway it should not affect the package's installation. Let me know if that's not the case. Cheers!
