### ISSUE TITLE
Can lightdm-webkit2-greeter access system battery level

### ISSUE THREAD

**Issue by FallingSnow** [Antergos/lightdm-webkit2-greeter#42]
I'm trying to show the battery level of my laptop in the login screen but webkit2gtk doesn't support the [battery api](http://caniuse.com/#feat=battery-status). I was wondering if there is a way to access it instead through lightdm. I'd prefer not having to make a server that must be started with the computer just to be polled for the battery level.

Thank you!

**Comment by lots0logs** [comment]
Hi,

I'm afraid LightDM does not offer any API to access the battery info. Perhaps you can suggest the feature upstream :smile: 

Cheers!
