### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by declanmarks** [Antergos/lightdm-webkit2-greeter#46]
I have install lightdm and lightdm-webkit2-greeter but every theme I use I get a blank screen and a cursor. The screen flashes grey before getting the black screen. Below are the configuration files:

lightdm-webkit2-greeter.conf

```
[greeter]
webkit-theme=material-lightdm
```

lightdm.conf

```
[SeatDefaults]
greeter-session=lightdm-webkit2-greeter
session-wrapper=/etc/lightdm/Xsession
```

I am currently using arch linux, xfce4 4.12.

**Comment by FallingSnow** [comment]
What is the output of `pacman -Q | grep webkit2gtk`. You should have at least `webkit2gtk` version `2.12.2-1`.

**Comment by declanmarks** [comment]
the output was:
webkit2gtk 2.12.2-1

So I don't think it is that.

**Comment by lots0logs** [comment]
@declanmarks Does it work with the default antergos theme?

**Comment by declanmarks** [comment]
No it doesn't. Below is a link to the logs and configuration, if it helps
https://drive.google.com/folderview?id=0Byz5L8W0RVl7eUpfaW01enRfLWs&usp=sharing

**Comment by lots0logs** [comment]
Could you make sure that you have the `accountsservice` package installed. If you do, reinstall it just to be safe.

**Comment by declanmarks** [comment]
I have accountsservice already installed. I have reinstalled it, That didn't work.

**Comment by lots0logs** [comment]
Is what you provided the entire contents of `/etc/lightdm.conf`? also, could you try enabling debug mode in `/etc/lightdm-webkit2-greeter.conf` and then post the logs?

**Comment by declanmarks** [comment]
Very strange, enabling debug mode made it work. I wonder if I did something else that fixed it.

**Comment by lots0logs** [comment]
That is indeed strange. Also its not the first time someone has mentioned that it only works when debug mode is enabled. There is definitely a bug here. Could you provide the output from when debug mode is not enabled vs when it is enabled?

**Comment by declanmarks** [comment]
Where is the output when debug mode is on.

**Comment by lots0logs** [comment]
It should be in `/var/log/lightdm/x-0-greeter.log`. Also you can right-click on the greeter and choose ***Inspect Element*** to view the webkit2gtk dev console. Let me know what you find!

**Comment by declanmarks** [comment]
I have put the file on google drive. 
https://drive.google.com/folderview?id=0Byz5L8W0RVl7eUpfaW01enRfLWs&usp=sharing
this google drive folder follows the same folder structure as my arch install.

**Comment by lots0logs** [comment]
@declanmarks Sorry for the delay. Could you try activating either the default Adwaita GTK theme or Numix Frost (if you have it installed). I think the issue might be related to the theme you are using. Let me know the result. Thanks.

**Comment by laxect** [comment]
i have same question with him. only the defualt theme can work.
And that happened only when i use modeset ( when i don't use it light-webkit2-greeter works well with all theme
