### ISSUE TITLE
fedora repo package has wrong dependence

### ISSUE THREAD

**Issue by cgh0st** [Antergos/lightdm-webkit2-greeter#50]
when i try to install the lightdm-webkit2-greeter package on fedora 23, an error occurred:
`nothing provides libgtk-3-0 needed by lightdm-webkit2-greeter-2.1.4-21.1.i686
`
it seems it should depend on gtk3, not libgtk-3-0.

**Comment by cgh0st** [comment]
both the copr repo and the OBS repo encountered the same problem.

**Comment by lots0logs** [comment]
@cgh0st COuld you give it another try and let me know if it works okay now? Thanks!

**Comment by cgh0st** [comment]
I get another error:
`
sudo dnf install lightdm-webkit2-greeter
Last metadata expiration check: 0:02:52 ago on Mon Jun 13 16:04:24 2016.
Error: nothing provides liblightdm-gobject-1-0 needed by lightdm-webkit2-greeter-2.1.3-6.1.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)
`
I saw a lightdm-gobject package, may be it is this one?

**Comment by cgh0st** [comment]
@lots0logs 
Hi, I checked the dependence of the package, it still have several issues:

    rpm -ivh --test lightdm-webkit2-greeter-2.1.4-25.1.x86_64.rpm 
    warning: lightdm-webkit2-greeter-2.1.4-25.1.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 7d771efd: NOKEY
    error: Failed dependencies:
    gnome-common is needed by lightdm-webkit2-greeter-2.1.4-25.1.x86_64
    liblightdm-gobject-1-0 is needed by lightdm-webkit2-greeter-2.1.4-25.1.x86_64
    webkit2gtk is needed by lightdm-webkit2-greeter-2.1.4-25.1.x86_64

**Comment by lots0logs** [comment]
@cgh0st Could you try it with `dnf`. Rpm does not resolve dependencies so that error might not be an actual problem. Let me know the result. Thanks.

**Comment by cgh0st** [comment]
@lots0logs 
Good work! I installed the updated package, the dependency issue seems solved. 

But it still has problem installing, here's another problem:
```
sudo dnf install lightdm-webkit2-greeter
Last metadata expiration check: 0:07:07 ago on Tue Jun 14 14:52:29 2016.
Dependencies resolved.
==============================================================================================================================================================================================
 Package                                            Arch                              Version                               Repository                                                   Size
==============================================================================================================================================================================================
Installing:
 lightdm-webkit2-greeter                            x86_64                            2.1.4-28.1                            antergos-lightdm-webkit2-greeter                            717 k

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total download size: 717 k
Installed size: 1.8 M
Is this ok [y/N]: y
Downloading Packages:
lightdm-webkit2-greeter-2.1.4-28.1.x86_64.rpm                                                                                                                  19 kB/s | 717 kB     00:37    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                          19 kB/s | 717 kB     00:37     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/bin from install of lightdm-webkit2-greeter-2.1.4-28.1.x86_64 conflicts with file from package filesystem-3.2-35.fc23.x86_64
  file /usr/lib from install of lightdm-webkit2-greeter-2.1.4-28.1.x86_64 conflicts with file from package filesystem-3.2-35.fc23.x86_64

Error Summary
-------------

```

**Comment by lots0logs** [comment]
@cgh0st Thanks for reporting back. I just built another package on OBS..I will build it on copr here shortly. Let me know how it goes. Cheers!

**Comment by cgh0st** [comment]
@lots0logs Cheers! I'm able to install without a problem now. Thanks.
