### ISSUE TITLE
Can't login via lightdm-webkit2-greeter but lightdm-gtk-greeter is OK

### ISSUE THREAD

**Issue by JackieMium** [Antergos/lightdm-webkit2-greeter#52]
Donno if this is the right place to ask. 
I am running Debian sid x86_64. I installed lightdm-webkit2-greeter and all the dependencies you provided and set greeter to webkit2-greeter.
My problem is that after I input my username and password and hit ENTER, nothing happens screen just stays at the same interface(same when I click Login button). I changed to lightdm-webkit2-greeter theme to `artur9010/lightdm-webkit-material` and `miko007/LightDM-Webkit-pantheon-theme` (all on GitHub) and the problem remains. As soon as I switch back to gtk-greeter I can successfully login. So I think this may have something to do with `lightdm-webkit2-greeter` itself.

**Comment by lots0logs** [comment]
Hi, I don't think the version of webkit2 in Debian is recent enough. Could you let me know which version you have? Also, enable debug mode in `/etc/lightdm/lightdm-webkit2-greeter.conf`, reproduce the issue a few times, and then post the log (its located at `/var/log/lightdm/x-0-greeter.log`)

**Comment by JackieMium** [comment]
@lots0logs I don't know what you mean that "the version of webkit2 in Debian is recent enough". I am using Debian sid and `ightdm-webkit2-greeter` is not in the official repo. I installed it myself via github(the `git clone --> make --> make install` procedure you provided). And I use `OpenBox` as my WM. I dno't have a DE.
Anyway, the problem is reproducible and I got the log files here:
`lightdm --show-config output:
```
   [Seat:*]
A  greeter-session=lightdm-webkit2-greeter
A  greeter-hide-users=false
A  session-wrapper=/etc/X11/Xsession

Sources:
A  /usr/share/lightdm/lightdm.conf.d/01_debian.conf
B  /etc/lightdm/lightdm.conf
```
`cat /usr/share/lightdm/lightdm.conf.d/01_debian.conf` output:
```
# Debian specific defaults
#
# - use lightdm-greeter session greeter, points to the etc-alternatives managed
# greeter
# - hide users list by default, we don't want to expose them
# - use Debian specific session wrapper, to gain support for
# /etc/X11/Xsession.d scripts

[SeatDefaults]
greeter-session=lightdm-webkit2-greeter
greeter-hide-users=false
session-wrapper=/etc/X11/Xsession
```
`cat /etc/lightdm/lightdm-webkit2-greeter.conf ` output:
```
# [greeter]
# webkit-theme = Webkit theme to use. (Default: antergos)
# debug_mode = Greeter theme debug mode. (Default: false)
# screensaver-timeout = Blank the screen after this many seconds of inactivity. (Default: 300)
# report-errors = Automatically report errors to the developers--anonymously. (Default: true)
#

[greeter]
#webkit-theme = pantheon
webkit-theme = material-lightdm
#webkit-theme = wisp
debug_mode = true
screensaver-timeout = 300
report-errors = false

#
# [branding]
# logo = Path to logo image for use by greeter themes.
# user_image = Default user image/avatar. This is used by greeter themes for users that have no .face image.
# background_images = Path to directory that contains background images for use by greeter themes.
#

[branding]
logo = /usr/share/lightdm-webkit/themes/antergos/img/antergos.png
user_image = /usr/share/lightdm-webkit/themes/antergos/img/antergos-logo-user.png
background_images = /usr/share/backgrounds
```
Three log files here:
lightdm.log : https://cfp.vim-cn.com/cbc7k
seat0-greeter.log:https://cfp.vim-cn.com/cbc7l
x-0.log:https://cfp.vim-cn.com/cbc7m

**Comment by JackieMium** [comment]
@lots0logs Yes, I have the `libwebkit2gtk-4.0-dev/unstable` at version `2.12.3-1`.
I changed the theme to `antergos` and problem remained. 
Here are the log:
lightdm.log:https://cfp.vim-cn.com/cbc7x
seat0-greeter.log:https://cfp.vim-cn.com/cbc7y
x-0.log file same as above.
I noticed there are `Authentication cancelled for adam` in the seat log. When I click login or press ENTER, nothing happens for a while.Then I click on the user name and the login process stops as the password go back to empty. So i don't think the `Authentication cancelled for adam` means anything. Maybe I am wrong, I don't know.

**Comment by lots0logs** [comment]
@JackieMium Hmm..what does this session execute: `lightdm-xsession`? Check the `.desktop` file in `/usr/share/xgreeters` if you arent sure.

**Comment by JackieMium** [comment]
@lots0logs 3 files in the `/usr/share/xgreeter` dir: `lightdm-greeter.desktop`, `lightdm-webkit2-greeter.desktop` and `lightdm-grk-greeter.desktop`. No `lightdm-xsession`.

**Comment by lots0logs** [comment]
@JackieMium I meant to say the xsessions directory, my bad :sweat_smile: . Which other sessions are available? Have you tried selecting one of the other sessions when logging in? What's the output of `ls -l /usr/bin | grep default`?

**Comment by JackieMium** [comment]
@lots0logs 
```
adam@MyDebian ~$ ls /usr/share/xsessions                                                                                                             
lightdm-xsession.desktop  openbox.desktop
adam@MyDebian ~$ ls -l /usr/bin | grep default                                                                                                       
-rwxr-xr-x 1 root   root       29840 Jun 30 06:50 defaults
-rwxr-xr-x 1 root   root         474 May 19 21:55 select-default-iwrap
-rwxr-xr-x 1 root   root        5602 Aug 27  2014 update-gconf-defaults
```
Default is Xsession in login mune. I tried switching between `Xsession` and `openbox` and nothing changed at all.

**Comment by lots0logs** [comment]
@JackieMium I don't have access to any Debian systems so its going to be difficult for me to identify the problem. Your logs indicate that you successfully authenticated several times but for some reason your session never started. There are no errors to give any clue as to what the problem may be. The next step I think is to enabled debug mode (which you have done already) and then after you input your password into the default greeter theme (`antergos`) right click anywhere on the screen and select `inspect element`. Then check the `console` tab for any warnings or errors. Let me know what you find.

**Comment by FedoraTipper** [comment]
I have the same problem as OP. Also on debian. I checked console and nothing is there other than the usual. What I did notice is that Gnome as the DE didn't change everytime I clicked my username.

**Comment by paescuj** [comment]
@JackieMium & @FedoraTipper I guess you've checked out the master branch and not the latest release, right? I can confirm that the login isn't working when using the master branch. But it is working using the latest release 2.1.4 (as described in the README).

@lots0logs Couldn't figure out the problem so far... Some change(s) since the last release seems to prevent the greeter from being able to log in - or is it working in your environment?
