### ISSUE TITLE
Black screen when using CSS3 3D transforms

### ISSUE THREAD

**Issue by NoiSek** [Antergos/lightdm-webkit2-greeter#54]
Using certain 3D transforms can cause the renderer to crash and display a black screen.

Reproduce with the following:
```
<!doctype html>
<html>
  <head>
    <style type="text/css">
      body {
        color: #fff;
        background: pink;
      }

      .cool {
        transform: rotateX(90deg);
      }
    </style>
  </head>
  <body>
    <div class="cool">
      Cool stuff. You should see pink.
    </div>
  </body>
</html>
```

**Comment by lots0logs** [comment]
Hi, which version of webkit2gtk do you have installed?

**Comment by NoiSek** [comment]
pacaur -Q | grep webkit

```
lightdm-webkit2-greeter 2.1.4-1
pywebkitgtk 1.1.8-3
qt5-webkit 5.7.0-1
webkit2gtk 2.12.3-1
webkitgtk 2.4.11-1
webkitgtk2 2.4.11-1
```

Somewhat confusing naming schemes. Hope that helps.

**Comment by lots0logs** [comment]
Could you enable debug mode in `/etc/lightdm/lightdm-webkit2-greeter.conf`, induce the crash a couple times, and then post the log here? (The log will be located at `/var/log/lightdm/x-0-greeter.log`)

**Comment by NoiSek** [comment]
I'm not getting any errors that I don't get normally (One on launching, one on force exiting).

Of the two, only this is a real error:
```
** (process:32018): WARNING **: Failed to open CK session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
Xlib:  extension "GLX" missing on display ":1".
```

As background info I'm using the 367.27-1 nvidia beta drivers, which come with 32 and 64 bit libgl.

Is it enough to run it via Xephyr with `lightdm --test-mode --debug` or will I have to log this the normal way? Avoiding doing that because it requires using a live distro to recover from.

**Comment by NoiSek** [comment]
If `transform: translateZ(0);` induces a crash, it's probably safe to say that anything GPU accelerated causes the problem, but it seems odd that it would work fine in-browser and not when logging in or testing, though. 

Definitely related to the GLX missing error in the above. Any way to figure out where it's looking for them?

Can confirm via the Xorg log that glx is being loaded properly:
```
4.713] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
```

**Comment by lots0logs** [comment]
Does this occur while running the greeter regularly (as in not with Xephyr)? Xephyr does not support GLX so testing using the lightdm test mode command isn't very useful. I saw something on the LightDM mailing list a couple weeks ago that its not possible to launch a greeter from an existing session without using Xephyr. I havent had time to dig into it to see what is necessary to enable the feature. Its on my TODO list though!

**Comment by NoiSek** [comment]
Wasn't willing to test it until just now, but it looks like it works!

Might be unrelated, but nvidia drivers disable indirect rendering by default:
```
[  4548.182] (II) Indirect GLX disabled.
```

Seems any GPU acceleration used in lightdm's test mode will cause a crash where it would work normally.

Thanks for being party to my nagging, seems I'm finally getting to the end.
![](https://cdn.discordapp.com/attachments/137649133455540224/200747095760699393/DeepinScreenshot20160707155642.png)

**Comment by lots0logs** [comment]
Awesome :+1: I need to remember to add something to the docs about testing with Xephyr because its not the same environment the greeter actually runs in so the results are not the same. I remember wasting more than a few hours on an issue that turned out not to be an issue myself. So I need to remember to add something to the docs for sure :sweat_smile:
