### ISSUE TITLE
I'm kind of really confused about the authentication process 

### ISSUE THREAD

**Issue by veggiedefender** [Antergos/lightdm-webkit2-greeter#57]
Reading the documentation, man pages, and other people's code hasn't helped me and has made me even more confused. I'm using angular for the nice two way binding and all. 

Here's my javascript:

```
var app = angular.module('cork', []);

app.controller('MainCtrl', [
'$scope',
function($scope){   
    $scope.users = lightdm.users;

    $scope.signIn = function () {
        lightdm.authenticate($scope.username);
    };
}]);

window.show_prompt = function(text, type) {    
    if(type === "password") {
        lightdm.respond($scope.password);
    }
};

window.show_message = function(text, type) {
    alert("show_message called");
};

window.authentication_complete = function() {
    if(lightdm.is_authenticated) {
        lightdm.start_session_sync();
    }
};

window.autologin_timer_expired = function() {
    alert("autologin_timer_expired called");
};
```

I'm not actually sure what some of the functions do, but I have some alerts to tell me when they are called.

My script makes it to the part where it responds the password, but it looks like `authentication_complete` never gets called.

I'd appreciate any insight. The full code is at https://github.com/veggiedefender/cork if you need it.

**Comment by lots0logs** [comment]
Hi, are you testing this using the `--test-mode` argument to lightdm command? That doesnt really work with this greeter. The best way to do testing during theme development is using a VM where you can actually boot into the greeter to test it without rebooting your physical system.

**Comment by veggiedefender** [comment]
I'm running `dm-tool add-nested-seat --screen 800x600` to test it

**Comment by lots0logs** [comment]
I havent had a chance to look at whats required for the greeter to support the new nested seats feature. I'm pretty sure there are some changes needed for it to work so that is probably what is causing the problem for you. Sorry!

**Comment by veggiedefender** [comment]
It's not working when I boot into my greeter either, so I think it's a problem with my implementation of the api rather than a problem with the test environment.

**Comment by lots0logs** [comment]
I don't see anything obviously wrong with your implementation, but I am not at all familiar with angular. Perhaps @artur9010 can take a look (he's familiar with angular).

**Comment by veggiedefender** [comment]
Wait! It won't be necessary. I found my bug and it's that my functions are defined outside of my controller so the password is outside of the scope.

Sorry for being a dumbass :/
