### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by FedoraTipper** [Antergos/lightdm-webkit2-greeter#58]
Hello,

So it seems my problem is kinda rare, as I cannot find it anywhere. I have successfully installed webkit, and edited lightdm.conf correctly. Upon booting to lightdm, everything is looks fine with webkit taking place over the default lightdm. Once I input my login details, nothing happens. It goes into a loading mode with the login screen still shown. Looking at the direct logs, it says that I have authenticated properly yet nothing has happened. This is whilst choosing deepin 15.2 or gnome 3.18 as DE options. 

When looking at x-0-greeter.log.old this is shown: (lightdm-webkit2-greeter:18742): Gdk-WARNING **: lightdm-webkit2-greeter: Fatal IO error 11 (Resource temporarily unavailable) on X server :0. 

Could anyone please help me with this?

**Comment by NoiSek** [comment]
The API for the webkit greeter has changed, it's possible you're using a theme that hasn't updated yet.

Which theme are you using?

**Comment by sebastiencs** [comment]
I have the same problem. I just install lightdm-webkit2-greeter on a new machine (Fedora 24 Cinnamon) with lightdm 1.10.6 installed on it.
I can't login. There is the loading icon but nothing happens.






[lightdm.log.old.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/374432/lightdm.log.old.txt)
[lightdm.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/374436/lightdm.log.txt)
[x-0.log.old.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/374433/x-0.log.old.txt)
[x-0.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/374434/x-0.log.txt)
[x-0-greeter.log.old.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/374435/x-0-greeter.log.old.txt)
[x-0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/374437/x-0-greeter.log.txt)

**Comment by lots0logs** [comment]
Hmm...That's a pretty old version of LightDM..Are you able to update to a more recent version by any chance?

**Comment by FedoraTipper** [comment]
I was using material theme. Could you please provide a link to the new version? What I downloaded was a clone.

**Comment by sebastiencs** [comment]
I updated LightDM to version 1.19.3 but it broke everything. What version do you have ?

**Comment by lots0logs** [comment]
@FedoraTipper Does the issue occur with the default `antergos` theme?

@sebastiencs The current stable version of lightdm is `1.18.2`

**Comment by sebastiencs** [comment]
It was a selinux issue.
Same problem with lightdm 1.19.3, I still can't login.
Also it's very slow, when I click on a button It reacts in 2 secondes...
What log do you need ? 
Here are the logs with lightdm 1.19.3




[lightdm.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/379900/lightdm.log.txt)
[seat0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/379902/seat0-greeter.log.txt)
[x-0.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/379903/x-0.log.txt)
[x-0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/379901/x-0-greeter.log.txt)
[x-2.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/379904/x-2.log.txt)

**Comment by lots0logs** [comment]
@sebastiencs Could you try using the latest stable version (the `1.19.x` series is a development series. They follow a similar versioning scheme to that of GNOME where even numbers are stable releases and odd numbers are unstable)? Also be sure you are using the default `antergos` theme as that's the official theme provided by the greeter. If you still experience issues please post the logs again so I can check them out. Thanks!

**Comment by sebastiencs** [comment]
I'm now using lightdm 1.18.2, same problem :(
Thanks for your help.

[lightdm.conf.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380431/lightdm.conf.txt)
[lightdm-webkit2-greeter.conf.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380430/lightdm-webkit2-greeter.conf.txt)
[lightdm.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380425/lightdm.log.txt)
[seat0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380426/seat0-greeter.log.txt)
[x-0.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380427/x-0.log.txt)
[x-0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380423/x-0-greeter.log.txt)
[x-2.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380424/x-2.log.txt)

**Comment by lots0logs** [comment]
@sebastiencs Could you enabled debug mode in the config file and grab the logs again? (Sorry I should have mentioned that before :grimacing: )

**Comment by sebastiencs** [comment]
Sure ;) :

[lightdm.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380474/lightdm.log.txt)
[seat0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380475/seat0-greeter.log.txt)
[x-0.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380478/x-0.log.txt)
[x-0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380476/x-0-greeter.log.txt)
[x-2.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/380477/x-2.log.txt)

**Comment by lots0logs** [comment]
@sebastiencs Thanks..could you check the x-0-greeter logs to see if you have one from when using the webkit2 greeter? The one you sent was from the gtk greeter. Also, what exactly happens when you try to log in. Walk me through it step by step (just a brief overview so I can be sure I understand the issue). Thanks!

**Comment by sebastiencs** [comment]
Oh yes x-0-greeter.log and x-2.log are old files, I didn't check their modification date.
The valid logs are lightdm.log, seat0-greeter.log and x-0.log
The logs for webkit2 greeter are in seat0-greeter.log, isn't it ?

When I try to login:
- I click on the date time
- My username appears, I click on it
- A box where I can type my password appears, I write it, then I click on "submit password" button
- The box with my password disappears, my username is still there
- Nothing happens
- I click again on my username
- The box with my password reappears with a loading icons

**Comment by lots0logs** [comment]
@sebastiencs Okay. Before trying to log in, right click anywhere on the screen and then click `Inspect Element`. Switch over to the `Console` tab and then try to log in. Let me know what (if any) messages you see in the console.

**Comment by sebastiencs** [comment]
When I open the console I see some warning message: "Unexpected CSS token"
When I click on my name there are some message about the session: "session for sebastien is undefined" (Same messages than in seat0-greeter.log)
When I click on "submit password" button, nothing happens in the console

**Comment by sebastiencs** [comment]
I checkout on 2.1.4 and now it works, I can login.
So it seems that something makes fail the login since this tag ?
However the UI is very slow: the screen is black for 3-4 seconds, buttons respond in 3 seconds, ...
Should I open an issue for that ?

**Comment by FedoraTipper** [comment]
@lots0logs I used the default antergos theme, I saw the browser console. Had no errors pop up or anything.

**Comment by lots0logs** [comment]
@sebastiencs Sorry I should have thought to ask you that in the beginning, The master branch is the development branch. Only official releases are guaranteed to be stable. Be sure to disable debug mode. That affects performance. If you still have trouble with performance open a new issue and include your system specs. Thanks!

@FedoraTipper Did you also install from master branch or did you install the latest official release?

**Comment by FedoraTipper** [comment]
@lots0logs I cloned the master branch

**Comment by lots0logs** [comment]
@FedoraTipper When the cursor changes to the X cursor it means the greeter has completely exited and your selected session is starting up. Any delay at that point is beyond the greeter's control I'm afraid.
