### ISSUE TITLE
Performance issue with modesetting

### ISSUE THREAD

**Issue by sebastiencs** [Antergos/lightdm-webkit2-greeter#61]
I have performance issue with lightdm-webkit2-greeter.
The background is black for 5 seconds, buttons respond in 3 secs...

It seems related to #30: When I disable modesetting, there is no problem.
But then I reactivated modesetting, tried lightdm-webkit-greeter and there is no problem with it.
So maybe lightdm-webkit-greeter do activate something you don't ? Or a flag set ?

Here is my conf: https://paste.fedoraproject.org/395714/53902014/

**Comment by lots0logs** [comment]
Any particular reason you are using modesetting? You should be using the intel driver directly and not modesetting.

**Comment by sebastiencs** [comment]
Actually modesetting is the only driver I can use.
My system have bugs with intel driver.

**Comment by FallingSnow** [comment]
I have the same issue. For some reason I can only use modesetting.

**Comment by FallingSnow** [comment]
I've been doing some reading and some suggest that intel drivers require modesetting.

**Comment by lots0logs** [comment]
@FallingSnow Could you provide reference links? Nothing I have read indicates that to be the case :confused:

**Comment by FallingSnow** [comment]
Yes sir. The first is the [arch wiki](https://wiki.archlinux.org/index.php/intel_graphics#Loading), first bullet point. The second I will have to find again.

Also, it has been fixed upstream. https://github.com/artur9010/lightdm-webkit-material/issues/30#issuecomment-240815962

**Comment by lots0logs** [comment]
I dont think that what is on the Arch Wiki about modesetting being the preferred driver for Intel graphics  is anything more than hearsay. AFAIK the Intel driver is still under active development by the folks at Intel and thus should be the driver of choice for anyone using Intel graphics. That being said, I will try to really dig into this and figure out what's up with it ASAP.

**Comment by FallingSnow** [comment]
I was talking sepecifically about the section that says
> Make sure you do not have nomodeset or vga= as a kernel parameter, since Intel requires kernel mode-setting.

**Comment by lots0logs** [comment]
I see. Kernel mode-setting is not the same thing as the modesetting driver :wink:

**Comment by FallingSnow** [comment]
I had a vibe that that was the case. Thanks for setting that straight.

**Comment by lots0logs** [comment]
This was fixed upstream.
