### ISSUE TITLE
Suggest changing to MIT license

### ISSUE THREAD

**Issue by newswim** [Antergos/lightdm-webkit2-greeter#68]
Hello,

Are the maintainers willing to entertain switching licenses?

**Comment by lots0logs** [comment]
Do you have any specific reasons why we might want to consider it?

**Comment by newswim** [comment]
I would like to display some additional information whenever the user logs in, and will likely need to modify the existing codebase a bit.

**Comment by lots0logs** [comment]
You can modify the code however you like under the current license. I see no need to change it. Sorry!
