### ISSUE TITLE
Manual login window in Antergos greeter

### ISSUE THREAD

**Issue by pszafer** [Antergos/lightdm-webkit2-greeter#7]
Hello,
Is it possible to show manual login greeter in this theme?
I have set
greeter-show-manual-login = true
and nothing change in this theme.

**Comment by karasu** [comment]
@pszafer : You entered your issue in the wrong package. Do not worry, I've added one myself in the correct one

See issue https://github.com/Antergos/lightdm-webkit-theme-antergos/issues/16

Cheers!
