### ISSUE TITLE
Broken with webkit2gtk

### ISSUE THREAD

**Issue by Ste74** [Antergos/lightdm-webkit2-greeter#72]
Title say all OS manjaro unstable : downgrade to webkit2gtk 2.12.3-1 solve the issue

**Comment by lots0logs** [comment]
With which version of webkit2gtk do you experience the problem? I'm currently using 2.12.4 and it works fine.

**Comment by Ste74** [comment]
Hi , my system is up to date to unstable branch on manjaro the problem appear with last 2.12.4 version : is only visible a white rectangular and a little triangular .. attached the lightdm --test-mode --debug : 
`[stefano@ste74 ~]$ lightdm --test-mode --debug
[+0.03s] DEBUG: Logging to /home/stefano/.cache/lightdm/log/lightdm.log
[+0.03s] DEBUG: Starting Light Display Manager 1.18.3, UID=1000 PID=3156
[+0.03s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.03s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.03s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.03s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.03s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.03s] DEBUG: Running in user mode
[+0.03s] DEBUG: Using Xephyr for X servers
[+0.03s] DEBUG: Registered seat module xlocal
[+0.03s] DEBUG: Registered seat module xremote
[+0.03s] DEBUG: Registered seat module unity
[+0.04s] DEBUG: Monitoring logind for seats
[+0.04s] DEBUG: New seat added from logind: seat0
[+0.04s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.04s] DEBUG: Seat seat0: Starting
[+0.04s] DEBUG: Seat seat0: Creating greeter session
[+0.04s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.04s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.05s] DEBUG: User /org/freedesktop/Accounts/User1002 added
[+0.05s] DEBUG: User /org/freedesktop/Accounts/User1001 added
[+0.05s] DEBUG: Seat seat0: Creating display server of type x
[+0.05s] DEBUG: Seat seat0: Starting local X display
[+0.05s] DEBUG: DisplayServer x-1: Logging to /home/stefano/.cache/lightdm/log/x-1.log
[+0.05s] DEBUG: DisplayServer x-1: Writing X server authority to /run/lightdm/root/:1
[+0.05s] WARNING: Error reading existing Xauthority: Failed to open file '/run/lightdm/root/:1': Permission denied
[+0.05s] WARNING: DisplayServer x-1: Failed to write authority: Failed to open X authority /run/lightdm/root/:1: Permission denied
[+0.05s] DEBUG: DisplayServer x-1: Launching X Server
[+0.05s] DEBUG: Launching process 3161: /usr/bin/Xephyr :1 -seat seat0 -auth /run/lightdm/root/:1 -nolisten tcp
[+0.05s] DEBUG: DisplayServer x-1: Waiting for ready signal from X server :1
[+0.05s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.05s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.05s] WARNING: Could not enumerate user data directory /var/lib/lightdm-data: Error opening directory '/var/lib/lightdm-data': Permission denied
[+1.11s] DEBUG: Got signal 10 from process 3161
[+1.11s] DEBUG: DisplayServer x-1: Got signal from X server :1
[+1.11s] DEBUG: DisplayServer x-1: Connecting to XServer :1
[+1.11s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+1.11s] DEBUG: Session: Not setting XDG_VTNR
[+1.11s] DEBUG: Session pid=3167: Started with service 'lightdm-greeter', username 'stefano'
[+1.13s] DEBUG: Session pid=3167: Authentication complete with return value 0: Success
[+1.13s] DEBUG: Seat seat0: Session authenticated, running command
[+1.13s] DEBUG: Session pid=3167: Not setting XDG_VTNR
[+1.13s] DEBUG: Session pid=3167: Running command /usr/bin/lightdm-webkit2-greeter
[+1.13s] DEBUG: Creating shared data directory /var/lib/lightdm-data/stefano
[+1.13s] WARNING: Could not create user data directory /var/lib/lightdm-data/stefano: Error creating directory: Permission denied
[+1.13s] DEBUG: Session pid=3167: Logging to /home/stefano/.cache/lightdm/log/seat0-greeter.log
[+1.62s] DEBUG: Greeter connected version=1.18.3 resettable=false

`

**Comment by lots0logs** [comment]
This greeter does not support lightdm's test mode. You have to run it as the greeter configured in lightdm.conf.

**Comment by Ste74** [comment]
Ok report when come back to home

**Comment by Ste74** [comment]
> This greeter does not support lightdm's test mode. You have to run it as the greeter configured in lightdm.conf.

Sorry but do you mean ? I searched in a  lightdm.conf but don't see a debug mode .. i set debug mode true in a lightdm-webkit2gtk-greeter.conf but i can't activate because not see "button"  this is what i see :\
![schermata del 2016-09-02 17-04-47](https://cloud.githubusercontent.com/assets/11218234/18208339/661b60cc-712f-11e6-9341-25fb1aec1a2b.png)
Plus is my greeter theme for system :p i see this in my real system

**Comment by Ste74** [comment]
I have installed the aur version and work . I have modified the theme [here](https://github.com/manjaro/packages-community/tree/master/lightdm-webkit2-greeter-manjaro) and not work ..

**Comment by lots0logs** [comment]
The AUR version is the last release. The master branch is the development branch. Test mode of lightdm is no longer supported. Did you try it in normal mode?

**Comment by Ste74** [comment]
You mean with false in debug mode in greeter? 
Il 02/set/2016 20:35, Dustin Falgout <notifications@github.com> ha scritto:The AUR version is the last release. The master branch is the development branch. Test mode of lightdm is no longer supported. Did you try it in normal mode?

**Comment by Ste74** [comment]
Ops not read all in email notification. Yes i try only 2.14.3 work in normal mode with 2.14.3 i have thesame look of xephyr.. i hve modified the pkgbuild of aur with sed to change color and .png for match with manjaro branding

**Comment by lots0logs** [comment]
Just to clarify you are having this issue using the latest official release version of the greeter (2.1.4)?

**Comment by Ste74** [comment]
Yes the last stable release 2.1.4 .. don't understand ..

**Comment by lots0logs** [comment]
Try to enable debug mode in `/etc/lightdm-webkit2-greeter.conf`, then reproduce the issue a couple times, and finally post the contents of `/var/log/lightdm/x-0-greeter.log` here.

**Comment by Ste74** [comment]
Hi seat0-greeter.log is empty but .old contain this
```

(lightdm-webkit2-greeter:752): Gtk-WARNING **: Allocating size to WebKitWebViewBase 0x1d26410 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lightdm-webkit2-greeter:752): Gtk-WARNING **: Allocating size to WebKitWebViewBase 0x1d26760 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
(lightdm-webkit2-greeter:752): Gtk-WARNING **: Allocating size to WebKitWebViewBase 0x1d26410 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lightdm-webkit2-greeter:752): Gtk-WARNING **: Allocating size to WebKitWebViewBase 0x1d26760 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lightdm-webkit2-greeter:752): Gdk-WARNING **: lightdm-webkit2-greeter: Fatal IO error 11 (Risorsa temporaneamente non disponibile) on X server :0.


(WebKitWebProcess:808): Gdk-WARNING **: WebKitWebProcess: Fatal IO error 11 (Risorsa temporaneamente non disponibile) on X server :0.


(WebKitDatabaseProcess:1829): Gdk-WARNING **: WebKitDatabaseProcess: Fatal IO error 11 (Risorsa temporaneamente non disponibile) on X server :0.
```

**Comment by lots0logs** [comment]
Do you see any errors in the webkit console (right click and then choose "Inspect Element")

**Comment by Ste74** [comment]
Here the photos
https://drive.google.com/file/d/0B8oHWi4jQCNaUmtFYTZkbmRJd0E/view?usp=sharing
https://drive.google.com/file/d/0B8oHWi4jQCNacFprNnRyT3prMWM/view?usp=sharing

**Comment by lots0logs** [comment]
Could you try downloading the original version of the theme and see if it works?

**Comment by Ste74** [comment]
Yeap , try now via yaourt and work fine :\

**Comment by lots0logs** [comment]
I think maybe you should try included the hash character (`#`) for the html hex colors in your sed commands.

**Comment by Ste74** [comment]
Ok , try it :p

**Comment by Ste74** [comment]
Nope 
Same result .. if i see in the debugger task i see the translation.js 
window.ant_translations = { 
ecc

**Comment by lots0logs** [comment]
Could you post your `/etc/lightdm/lightdm-webkit2-greeter.conf` here?

**Comment by Ste74** [comment]
Here and thank you for your time 
```
#
# [greeter]
# webkit-theme = Webkit theme to use. (Default: manjaro)
# debug_mode = Greeter theme debug mode. (Default: false)
# screensaver-timeout = Blank the screen after this many seconds of inactivity. (Default: 300)
#

[greeter]
webkit-theme = manjaro
debug_mode = true
screensaver-timeout = 300

#
# [branding]
# logo = Path to logo image for use by greeter themes.
# user_image = Default user image/avatar. This is used by greeter themes for users that have no .face image.
# background_images = Path to directory that contains background images for use by greeter themes.
#

[branding]
logo = /usr/share/lightdm-webkit/themes/manjaro/img/manjaro.png
user_image = /usr/share/lightdm-webkit/themes/manjaro/img/manjaro-logo-user.png
background_images = /usr/share/backgrounds
```

**Comment by lots0logs** [comment]
Could you confirm that both of these files exist in your system?
```
logo = /usr/share/lightdm-webkit/themes/manjaro/img/manjaro.png
user_image = /usr/share/lightdm-webkit/themes/manjaro/img/manjaro-logo-user.png
```

**Comment by Ste74** [comment]
Yes 
```
[stefano@ste74 ~]$ ls /usr/share/lightdm-webkit/themes/manjaro/img
fallback_bg.jpg  manjaro-logo-user.png  manjaro.png
```
with **webkit2gtk 2.12.3** all work fine with **2.12.4**  is this strange

**Comment by lots0logs** [comment]
But it does work with the default theme and 2.12.4 correct? I think this has something to do with the way you packaged it. Honestly the appropriate method by which to achieve your desired result would be to package the greeter exactly as it is provided by default and then to package a separate copy of the theme where you modify it specifically for Manjaro.

**Comment by Ste74** [comment]
Yep after see the debug task and view togheter antergos i have try to modified the sed instruction to found all antergos refer into theme folder .. now work with a charme :smile: 
i think i can close via 
https://github.com/manjaro/packages-community/commit/fb145dc45ef312becb2708e02190db685573bf54
