### ISSUE TITLE
Authentication cancelled for dad

### ISSUE THREAD

**Issue by fossfreedom** [Antergos/lightdm-webkit2-greeter#73]
ok - very similar to #52 

the logs are slightly different though - I'm using ubuntu 16.04 "budgie-remix" with the latest master built source.

I noticed the unusual "Authentication cancelled for dad" in the log - looks like each time I hit the enter key authentication fails?  Very strange because under lightdm-gtk-greeter, same password works.

Any thoughts?  Happy to debug anything - just shout.

thanks
[lightdm.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/450752/lightdm.log.txt)
[seat0-greeter.log.txt](https://github.com/Antergos/lightdm-webkit2-greeter/files/450751/seat0-greeter.log.txt)

**Comment by fossfreedom** [comment]
can confirm v2.1.4 works in ubuntu 16.04 "budgie-remix" - so the master branch is currently broken.

**Comment by lots0logs** [comment]
Hi, sorry for the delayed response.  The master branch is the development branch (thus its volatile). Only official releases are guaranteed stable.

**Comment by fossfreedom** [comment]
Yeah no worries.  I am willing to help out to debug anything ... Just shout :)

On 15 Sep 2016 02:18, Dustin Falgout <notifications@github.com> wrote:

Hi, sorry for the delayed response. The master branch is the development branch (thus its volatile). Only official releases are guaranteed stable.
