### ISSUE TITLE
very bad performance in ubuntu

### ISSUE THREAD

**Issue by GreenJoey** [Antergos/lightdm-webkit2-greeter#75]
I installed this greeter in ubuntu 16.04 (as antergos was not booting into gui in my laptop)
the first thing i noticed that it was very slow ,slower than a turtle also the greeter didn't allow me to choose my desktop session and started the default session

**Comment by lots0logs** [comment]
Was this while using the default theme? What are your system specs? Could you post links to the logs (located in `/var/log/lightdm`)

**Comment by GreenJoey** [comment]
My System specs are 
i5-5005U  2.0  GHz x 4
3.8 Gib DDR3 RAM

**Comment by lots0logs** [comment]
Where's the logs?

**Comment by GreenJoey** [comment]
I am sorry but I uninstalled <b>Ubuntu</b> for <i><b>Manjaro</b></i>
