### ISSUE TITLE
cannot compile v2.1.4 in Ubuntu 16.10

### ISSUE THREAD

**Issue by fossfreedom** [Antergos/lightdm-webkit2-greeter#76]
Ubuntu 16.10 uses GTK3.20

when compiling I get the following error log:
https://launchpadlibrarian.net/284512714/buildlog_ubuntu-yakkety-i386.lightdm-webkit2-greeter_2.1.4-0ubuntu1+yakkety001_BUILDING.txt.gz

The same package works great under Ubuntu 16.04 (GTK3.18)

I guess there must be a newer version of lightdm in Ubuntu 16.10.

Any ideas how to patch v2.1.4 to make it compile under 16.10?

**Comment by lots0logs** [comment]
@fossfreedom Could you try compiling again using the new instructions in the README? Let me know how it goes. Thanks.

**Comment by fossfreedom** [comment]
sure - will do - v2.1.4 or the master branch?

**Comment by lots0logs** [comment]
master..thanks :smiley:

**Comment by fossfreedom** [comment]
oh dear - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795253

Debian does not support meson builds at the moment

Can I build this any other way?

**Comment by lots0logs** [comment]
I admit I am not very familiar with debian packaging though you should be able to build it on Ubuntu (I'm already doing that in our CI tests right now)

**Comment by fossfreedom** [comment]
sure - yes I can manually compile using meson under both Debian and Ubuntu.  I'll try that on 16.10 tonight.

I intend though to submit lightdm-webkit2-greeter to both Debian and Ubuntu so that it is available directly from their repositories - you may be aware very few debian and ubuntu users (apart from the more adventurous) install third-party repos such as the OBS repos.

**Comment by lots0logs** [comment]
What we are working towards is replacing the current package for the webkit1 greeter with a new package for the webkit2 greeter. More details here: https://bugs.launchpad.net/lightdm-webkit-greeter/+bug/1588150

**Comment by fossfreedom** [comment]
understood - FYI - I was looking to add a lightdm-webkit2-greeter for our distro budgie-remix based on 16.10.  I'll hold off from packaging because it sounds like you've got this well in hand.  Cheers.

Onto matters - I've retried the meson method (it is amazing how fast this is to compile!!) - similar errors as the old packaging errors as described in the first comment at the top of this issue.

piccy here

![screenshot from 2016-10-10 19-59-49](https://cloud.githubusercontent.com/assets/996240/19247735/87099804-8f24-11e6-900a-8ea3a4e9e535.png)

Looking at the changelog on the lightdm package in ubuntu 16.10 - it appears all api's include an error parameter 

http://changelogs.ubuntu.com/changelogs/pool/main/l/lightdm/lightdm_1.19.5-0ubuntu1/changelog

this entry:

* Report errors for all liblightdm methods. This will require existing
      greeters to update their API usage. The ABI is unchanged.

**Comment by lots0logs** [comment]
@fossfreedom This should be fixed now. Let me know if you still have trouble :smiley:

**Comment by fossfreedom** [comment]
nicely done!

can confirm - all works on ubuntu 16.10.  Cheers!
