### ISSUE TITLE
cannot input login password

### ISSUE THREAD

**Issue by devland** [Antergos/lightdm-webkit2-greeter#78]
Lots of packages just got updated, including webkit2gtk and some gnome packages.
Since then I am unable to input any text in the login screen. The textbox just doesn't focus no matter how many times I click on it.
Is there any other way to login?
Can this be fixed?
I am using the cinnamon DE.

**Comment by lots0logs** [comment]
Hi, I noticed the issue earlier today. It has something to do with the rendering of the focus state of the input field. As a temporary work-around try resetting it (in the dropdown menu there is a reset button). After one or two resets it seems to work. I'll be looking further into the issue as soon as I can.

**Comment by devland** [comment]
The reset button only worked once. Since then I've tried dozens of times with no luck.
Thanks for looking into this. :)

**Comment by ArchangeGabriel** [comment]
Doesn’t work here. I keep hitting reset, but it never works. Can’t get into my session, which is quite annoying. I suppose rolling back could be a solution, but might not be easy considering the number of gtk packages that were upgraded…

BTW, if I click on the arrow, after a while it just show an empty red area with a little clickable cross that bring back to user choice screen. I suppose it should have some text in there. That was already the case before today update, but I thought I would mention it while posting here.

**Comment by ArchangeGabriel** [comment]
Switched to a TTY, installed lightdm-gtk-greeter and configured lightdm to use it, restarting lightdm didn’t worked but rebooting did.

**Comment by dmp1ce** [comment]
Possible workaround here: https://forum.antergos.com/topic/5075/testers-needed-mate-1-16/4

**Comment by lots0logs** [comment]
If anyone has time to test the latest code for the default theme against this issue it would be much appreciated. Simply download this repo and then copy the theme directory over to `/etc/lightdm/themes/`. I dont expect there to be any problems with the latest theme code but just to be safe its probably best if you copy it to a separate directory and then update your `/etc/lightdm/lightdm-webkit2-greeter.conf` accordingly.

**Comment by devland** [comment]
@dmp1ce I just tried the crazy workaround in your thread.
1. Drag and drop some selected text from the greeting. The welcome text should do.
2. Reset the whole thing as @lots0logs instructed.
3. Repeat 1.
You should now be able to edit the text in the password box. :)

**Comment by dpeukert** [comment]
@lots0logs `/etc/lightdm/themes` doesn't work, but `/usr/share/lightdm-webkit/themes` does (maybe this has higher priority?).

**Comment by lots0logs** [comment]
> @lots0logs /etc/lightdm/themes doesn't work, but /usr/share/lightdm-webkit/themes does (maybe this has higher priority?).
> EDIT: Stopped working.

Typo..sorry :grimacing:

**Comment by ShapeShifter499** [comment]
I followed a solution similar to @ArchangeGabriel. I basically removed all of lightdm and then reinstalled it with lightdm-gtk-greeter.

**Comment by ahomatthew** [comment]
Also having this issue -- not sure if this helps, but if you drag your "username" into the input area, you can get a cursor on it.  I just fell back to the gtk greeter for the time being.

**Comment by phdd** [comment]
Having the same issue, I noticed that there's no Keyboard input recognized at all. If you right click anywhere, there should be a _reload_ button. After refreshing the view everything's working as expected. At least for me.

**Comment by sfantu** [comment]
I also had the same issue but after i rebooted the hole screen was black.
