### ISSUE TITLE
buiding on fedora22

### ISSUE THREAD

**Issue by vladnosferatu** [Antergos/lightdm-webkit2-greeter#8]
hello

i have this " No package 'liblightdm-gobject-1' found "

but i have 
/usr/lib64/liblightdm-gobject-1.so.0
/usr/lib64/liblightdm-gobject-1.so.0.0.0

can you help me with this ?

thanks

**Comment by lots0logs** [comment]
Hi,

Arch uses `/usr`, /usr/bin`, and `/usr/lb` for installing package files. Did you run configure with the appropriate paths for fedora? If I remember correctly the command argument is `--libdir /lib64`

**Comment by vladnosferatu** [comment]
yes, with  no success
found my problem

i dont have the this dir /usr/include/lightdm-gobject-1/

and this file /usr/lib64/pkgconfig/liblightdm-gobject-1.pc

**Comment by lots0logs** [comment]
You may need to install a dev package for lightdm if one is available. I havent used Fedora in a while but I know on Ubuntu they always create separate packages for dev/debug files.

**Comment by vladnosferatu** [comment]
i only have this,
and have it all

Last metadata expiration check performed 1 day, 2:02:40 ago on Fri Jul 10 18:39:08 2015.
=================================================================== N/S Matched: lightdm ===================================================================
lightdm.x86_64 : Lightweight Display Manager
lightdm-kde.x86_64 : LightDM KDE Greeter
lightdm-gtk.x86_64 : LightDM GTK3 Greeter
lightdm-qt.x86_64 : LightDM QT client library
lightdm-qt.i686 : LightDM QT client library
lightdm-gobject.x86_64 : LightDM GObject client library
lightdm-gobject.i686 : LightDM GObject client library
lightdm-gtk-common.noarch : Common files for lightdm-gtk
lightdm-qt-devel.x86_64 : Development files for lightdm-qt
lightdm-qt-devel.i686 : Development files for lightdm-qt
lightdm-gobject-devel.i686 : Development files for lightdm-gobject
lightdm-gobject-devel.x86_64 : Development files for lightdm-gobject
lightdm-razorqt.x86_64 : LightDM greeter that uses the Razor-qt (Qt based) lib kit
system-switch-displaymanager.noarch : A display manager switcher for GDM, KDM, XDM, WDM and LightDM

**Comment by lots0logs** [comment]
Seems like this should be it: `lightdm-gobject-devel.x86_64 `
