### ISSUE TITLE
Doesn't respond when cursor in secondary monitor.

### ISSUE THREAD

**Issue by Edujg** [Antergos/lightdm-webkit2-greeter#82]
As the title mentions, I need to move the cursor from secondary to primary monitor to start interacting with the greeter. Primary monitor is the laptop's one which I only use to login.

As I remember, before it wasn't needed. I just pushed 'enter' twice (as unique user) and started writing the password. It's not something very important but it was more practical.

Thanks a lot for reading.

**Comment by lots0logs** [comment]
Hmm..The mouse cursor should appear on the same display as the greeter when it starts. If you use your external display as your primary then it should all work correctly automatically. Which OS and desktop environment are you using? Which versions? What about GTK version?

**Comment by Edujg** [comment]
I'm using Antergos with GNOME 3.22.1. GTK version 3.22.1.

**Comment by lots0logs** [comment]
Could you post the output of the following command: `xrandr`

**Comment by Edujg** [comment]
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
LVDS connected (normal left inverted right x axis y axis)
   1366x768      60.03 +
   1280x720      59.86  
   1152x768      59.78  
   1024x768      59.92  
   800x600       59.86  
   848x480       59.66  
   720x480       59.71  
   640x480       59.38  
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1600x1200     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
VGA-0 disconnected (normal left inverted right x axis y axis)

**Comment by lots0logs** [comment]
Okay. You can make lightdm use your external display as the primary by doing the following:

1. Create the following file:
  * **/etc/lightdm/display.sh**
  ```sh
  #!/bin/bash
  
  xrandr --output HDMI-0 --primary --output LVDS --left-of HDMI-0
  ```
2. Make the file executable: `sudo chmod +x /etc/lightdm/display.sh`
3. Edit `/etc/lightdm/lightdm.conf`:
  * Change the 2<sup>nd</sup> occurrence of this line:
   ```
   #display-setup-script=
   ```
   with the following:
   ```
   display-setup-script=/etc/lightdm/display.sh
   ```

Let me know if that takes care of the issue for you :smiley:

**Comment by Edujg** [comment]
Thanks a lot @lots0logs , it works perfectly!!

I also appreciate the lesson about _xrandr_ and _lightdm.conf_ ;)
