### ISSUE TITLE
Problem with login screen

### ISSUE THREAD

**Issue by santagu** [Antergos/lightdm-webkit2-greeter#85]
Good morning, I can not block session nor enable the login screen with user and password.

When I log in automatically without prompting for username and password everything works. When I lock or enable sesion login screen it goes black, but the console works. If I reboot (wihout session login screen) starts well.

Problem with login screen.

Good morning, I can not block session nor enable the login screen with user and password. When I log in automatically without prompting for username and password everything works. When I lock or enable login with user and key to screen it stays black, but the console works. If I reboot (as bypasses the home screen) starts well.

I think it's a problem with lighdm but I do not know what logs to send or what to look at.

The problem appeared a week ago when I updated the system (with pacman -Suy). Before this the system worked fine. I have reinstalled the system but it only works if I enable (in installation) "don't ask user and password" option.

I think it's a problem with lighdm but I do not know what logs to send or what to look at. I have a nvidia graphic card.

Please help me.

Thanks very much in advance.

**Comment by santagu** [comment]
The output os lspci for my graphics card:

01:00.0 VGA compatible controller: NVIDIA Corporation GT218 [GeForce 210] (rev a2) (prog-if 00 [VGA controller])
	Subsystem: Gigabyte Technology Co., Ltd Device 3525
	Flags: bus master, fast devsel, latency 0, IRQ 34
	Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nouveau
	Kernel modules: nouveau

**Comment by lots0logs** [comment]
Hi, could you try running `pacman -Syyu` and then rebooting to see if the issue remains? If so, grab the contents of `/var/log/lightdm/seat-0-greeter.log` and post a [paste2](http://paste2.org) link to it here.

**Comment by santagu** [comment]
Thanks but the problem continues. I'm block my session and the screen goes first white (1 second) and the goes black.

The /var/log/lightdm/seat-0-greeter.log is in http://paste2.org/0caFPgZp

**Comment by lots0logs** [comment]
Could you try using the nvidia drivers instead of nouveau? You can do it with:
```sh
sudo pacman -Rdd xf86-video-nouveau mesa
sudo pacman -S   nvidia-340xx nvidia-340xx-libgl
```
Then reboot. Let me know how it goes.

**Comment by santagu** [comment]
upppss!!! Now when the system boot I see nothing, the screen goes black. I can not even see the console with alt-Fx ...

**Comment by santagu** [comment]
In .xsession-errors appears this error:
/usr/bin/light-locker: error while loading shared libraries: libwayland-egl.so.1: cannot open shared object file: No such file or directory

**Comment by santagu** [comment]
SOLVED!!!! Thanks very much.

It was almost solved but something was missing.

It looks like it was indeed a problem with generic nvidia drivers. I have tried reinstalling antergos but this time with the proprietary drivers (instead of noveau) to see if the installation wizard install something more and now if it works.

I pass you the list of packages that are installed because I think it was missing some more to install:
lib32-nvidia-340xx-libgl
lib32-nvidia-340xx-utils
nvidia-340xx
nvidia-340xx-libgl
nvidia-340xx-utils

Thanks very much!!!

**Comment by santagu** [comment]
For me, the issue can be closed, unless you want more information. 
The support you give is the best of all the distributions I've tried.
Thanks again.
