### ISSUE TITLE
Possible mock.js mistake

### ISSUE THREAD

**Issue by FallingSnow** [Antergos/lightdm-webkit2-greeter#88]
Is [this line](https://github.com/Antergos/lightdm-webkit2-greeter/blob/master/themes/_vendor/js/mock.js#L481) supposed to be `if ( !('lightdm' in window) )` instead of the current `if ( ! 'lightdm' in window )`?

**Comment by lots0logs** [comment]
Yep, you are right! 

![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/20582385/6877fd5a-b1a6-11e6-99c2-d45ae2ec12fb.gif)

**Comment by FallingSnow** [comment]
@lots0logs Could you give me a little guidance on how to use mock.js. I'm trying to use it via `require('mock.js') `. I get `ReferenceError: LightDMGreeter is not defined`.

**Comment by lots0logs** [comment]
Actually the mock.js doesn't work right now. I kind of broke it a bit while shuffling stuff around. Though I don't think we need it anymore because its now possible to interact directly with the greeter and LightDM from within your user session. All you have to do is add a line to the `.desktop` file for your session. I use cinnamon so the file for me is `/usr/share/xsessions/cinnamon.desktop`. The line to add is: `X-LightDM-Allow-Greeter=true`. You have to restart lightdm after editing the desktop file. Then you should be able to simply launch the greeter from a terminal `lightdm-webkit2-greeter`

**Comment by FallingSnow** [comment]
I see. Thanks for letting me know. I tried using `lightdm-webkit2-greeter` but I get much better performance and less artifacts with `dm-tool add-nested-seat --screen 1920x1080`.

**Comment by lots0logs** [comment]
Hmm..I wasn't aware of that dm-tool option. Simply launching the greeter itself works fine for me. No performance problems once so ever :eyes:  Anyway, I think that I changed my mind on not keeping `mock.js` script. Its useful for creating greeter theme demos that can be accessed in normal web browsers so I'll try to fix it soon.

**Comment by FallingSnow** [comment]
Idk, I switched back to the modesetting driver because I get much better chromium performance (among other things). Perhaps that is the cause of the poor performance. I also have a 4k display which creates artifacts when using `lightdm-webkit2-greeter` compared to `dm-tool add-nested-seat --screen 1920x1080`. Anyway, thanks as always @lots0logs.

**Comment by lots0logs** [comment]
@FallingSnow Just fyi, the performance issue with webkitgtk and the intel driver has been fixed. I'm not sure about Chromium though.

**Comment by FallingSnow** [comment]
I've known about the performance fix, it only fixed performance being abysmal. But I had performance issues before that regression. I believe it has to do with my screen being 4k.

I'm doing a rewrite of the material theme in react so we'll see if the performance was something associated with the angular version or the issue is something deeper (I assume it's something deeper).

**Comment by lots0logs** [comment]
> I'm doing a rewrite of the material theme in react

Nice! I've been wanting to rewrite the default theme in react but havent found the time yet. Let me know how yours turns out :smiley:

**Comment by FallingSnow** [comment]
No, I've been using `lightdm-webkit2-greeter-2.1.6-1`. Is there a quick and easy way to install the master branch on arch?

**Comment by lots0logs** [comment]
Sure, there's a package in [our repo](http://build.antergos.com/repo/browse/main) called `lightdm-webkit2-greeter-next`

**Comment by FallingSnow** [comment]
Got it installed. I'll use it from here on out and let you know if I run into any issues.
