### ISSUE TITLE
lightdm-webkit2-greeter-next does not show users

### ISSUE THREAD

**Issue by FallingSnow** [Antergos/lightdm-webkit2-greeter#91]
Just restarted my computer today, got to a login screen which seemed to load a mock login with Clark Kent. I'm using the [material theme](https://github.com/artur9010/lightdm-webkit-material). It would seem that the new greeter did not load lightdm as a global variable causing the theme to believe it was in "demo mode".

Downgrading the 2.1.6-1 fixes this.

**Comment by lots0logs** [comment]
Could you post the logs? Thanks.

**Comment by FallingSnow** [comment]
Ok, seems to be fixed. I have however noticed now that a warning about the theme not working correctly with the possibility to change themes always pops up. I haven't actually tried to sign in with the material theme but it seems to functioning normally.

**Comment by lots0logs** [comment]
@FallingSnow The notice is part of a new safe guard I implemented to try and ensure that users are never stuck at the login screen unable to log in due to theme errors. If the notice is getting triggered its because there are errors being output to the console in the theme's javascript execution environment.

**Comment by FallingSnow** [comment]
I see, then it appears to be working as expected.

Another issue I ran into (I'll have to double check), when using the currently released material theme you are unable to sign in. I believe this is due to the change from `lightdm.start_authentication(user)` to `lightdm.authenticate(user)`.

**Comment by lots0logs** [comment]
>I believe this is due to the change from lightdm.start_authentication(user) to lightdm.authenticate(user).
Indeed. I think I am going to add a shim for that old method for just one release cycle since the material theme is pretty popular.

**Comment by FallingSnow** [comment]
Yeah I would say just deprecate it, don't remove it.

**Comment by lots0logs** [comment]
Its actually been deprecated since version 2.0.0. I wanted to remove it for 2.2 thinking its been enough time but I guess one more cycle can't hurt.

**Comment by FallingSnow** [comment]
Haha, then I guess it being in material is my fault, sorry about that.

On another note, does the fallback prompt trigger if there is a warning, because I was just prompted and the console only has a warning.

**Comment by lots0logs** [comment]
Well, ideally no it wouldnt. But there is no way to tell with any certainty the level of the message. Even though the webkit2 console api says it tells you the level I discovered that its doesnt work right. So what we're doing currently is checking for the phrase "Error" or "Exception" in any console message.
