### ISSUE TITLE
An error detected in the current theme that could interfere with the system login process...

### ISSUE THREAD

**Issue by mrmodolo** [Antergos/lightdm-webkit2-greeter#98]
Options:
* Load Default Theme
* Load Fallback Theme
* Cancelar
 If I choose 'Load Default Theme' I go to the login screen but my user does not show but the avatar!

SO: Antergos (Arch)
100% updated
Kernel 4.8.13-1-ARCH

**Comment by lots0logs** [comment]
Hi. Could you try enabling debug mode in `/etc/lightdm/lightdm-webkit2-greeter.conf` and then induce the issue a couple times. After that, post the contents of `/var/log/lightdm/seat-0-greeter.log` here.

**Comment by mrmodolo** [comment]
Hi!

I believe the error is indicated in the seat-0-greeter.log file. I'm sending the files that are in the / var / log / lightdm / * folder. I activated debug mode.

[logs.zip](https://github.com/Antergos/lightdm-webkit2-greeter/files/670766/logs.zip)

**Comment by lots0logs** [comment]
Hmm..could you try checking the webkit dev console for errors? (right-click anywhere on the login screen and choose "Inspect Element". Then click the "Console" tab).

**Comment by mrmodolo** [comment]
I'm at work now...
As soon as I get home I'll try what you said.

**Comment by mrmodolo** [comment]
Hi!

I have a lot of Unexpected CSS token:: font-awesome.min.css:4:1655
1820, 1988, ... etc

filter: progid: DXImageTransform.Microsoft.BasicImage(rotation=3);

**Comment by lots0logs** [comment]
About how many seconds does it take for the login screen to load?

**Comment by mrmodolo** [comment]
Merry Christmas!

After the systemd boots up, about 31 seconds for the error message to appear!

If I do the reload from the window preview element, 3 seconds.

**Comment by lots0logs** [comment]
Could you try installing this version and let me know if the issue persists?

http://repo.antergos.info/iso/testing/uefi/antergos-staging/x86_64/lightdm-webkit2-greeter-next-2.2.1beta1-1-x86_64.pkg.tar.xz

**Comment by mrmodolo** [comment]
Hi!

Now the error message no longer appears! But I still do not see the avatars!
I'm sending some photos. Is there a way to do a printscreen while on login screen?

Thank you for your help!
![foto01_](https://cloud.githubusercontent.com/assets/1923174/21471146/7de02612-ca8e-11e6-8a1f-f63b3560a66e.png)
![foto02_](https://cloud.githubusercontent.com/assets/1923174/21471147/7de4d96e-ca8e-11e6-898f-6d5065d53ac0.png)
![foto03_](https://cloud.githubusercontent.com/assets/1923174/21471145/7ddfb998-ca8e-11e6-854b-b84d5499a0e4.png)

**Comment by jonathanio** [comment]
I've just updated to 2.2 myself on Arch and I'm seeing the same issue.

**Comment by lots0logs** [comment]
@mrmodolo Could you post the contents of `/etc/lightdm/lightdm-webkit2-greeter.conf`?

@jonathanio Are you referring to the Error Recovery Dialog always showing up or the avatar not showing up? Have you tried installing the test version I provided in my previous comment?

**Comment by jonathanio** [comment]
@lots0logs Yeah.

Initially I had just a blank screen as I was still using my custom configuration from the previous build which was only changed to use "material" as the theme. When I replaced it with the `.pacnew` version of the `.conf` file I received the error dialog asking if I want to load the Default or Fallback themes.

For the moment i've reverted back to the previous version to log in, but I'll try the beta version now.

**Comment by lots0logs** [comment]
@jonathanio I think the material theme is broken due to it not being updated to be compatible with changes in the greeter. You should have been able to choose "Load Default Theme" in the error dialog to login without having to downgrade the package. Its actually the entire purpose of that dialog so if its not functioning as I described please let me know. Thanks!

**Comment by mrmodolo** [comment]
Hi!

Sorry!

Yes, I installed the version you sent (sudo pacman -U ...).
After I installed the version you sent the error dialog did not appear anymore.
The only problem now is the avatars that do not appear. This was happening before too.

**Comment by lots0logs** [comment]
@minijackson Right, I understood that much :wink:  As far as the avatar not showing up, could you post your greeter config file here? Thanks.

**Comment by mrmodolo** [comment]
I've tried different types of avatars. JPEG and PNG and the result was the same. What I noticed is that the images used for the avatars are 96x96 in size!

**Comment by jonathanio** [comment]
@lots0logs when I replaced the config file it was with the defaults. Interestingly, I'm seeing the following in the logs:

```
Dec 25 12:28:23 gwyn kernel: traps: WebKitWebProces[1915] trap int3 ip:7fb2b981cff1 sp:7ffcf86b5bc0 error:0
Dec 25 12:28:23 gwyn systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Dec 25 12:28:23 gwyn systemd[1]: Started Process Core Dump (PID 1930/UID 0).
Dec 25 12:28:23 gwyn systemd-coredump[1931]: Process 1915 (WebKitWebProces) of user 620 dumped core.

                                             Stack trace of thread 1915:
                                             #0  0x00007fb2b981cff1 n/a (libglib-2.0.so.0)
                                             #1  0x00007fb2b981e047 g_log_default_handler (libglib-2.0.so.0)
                                             #2  0x00007fb2b981e354 g_logv (libglib-2.0.so.0)
                                             #3  0x00007fb2b981e55f g_log (libglib-2.0.so.0)
                                             #4  0x00007fb26517ddb7 n/a (liblightdm-webkit2-greeter-webext.so)
                                             #5  0x00007fb26517e2b2 webkit_web_extension_initialize (liblightdm-webkit2-greeter-webext.so)
                                             #6  0x00007fb2bc41a627 n/a (libwebkit2gtk-4.0.so.37)
                                             #7  0x00007fb2bc41a85d _ZN6WebKit22WebGtkExtensionManager10initializeEPK14OpaqueWKBundlePKv (libwebkit2gtk-
                                             #8  0x00007fb2bc40d776 n/a (libwebkit2gtk-4.0.so.37)
                                             #9  0x00007fb2bc284696 n/a (libwebkit2gtk-4.0.so.37)
                                             #10 0x00007fb2bc26c036 n/a (libwebkit2gtk-4.0.so.37)
                                             #11 0x00007fb2bc470562 n/a (libwebkit2gtk-4.0.so.37)
                                             #12 0x00007fb2bc46f298 n/a (libwebkit2gtk-4.0.so.37)
                                             #13 0x00007fb2bc12c9e6 n/a (libwebkit2gtk-4.0.so.37)
                                             #14 0x00007fb2bc12da58 n/a (libwebkit2gtk-4.0.so.37)
                                             #15 0x00007fb2b93a2d65 _ZN3WTF7RunLoop11performWorkEv (libjavascriptcoregtk-4.0.so.18)
                                             #16 0x00007fb2b93d9209 n/a (libjavascriptcoregtk-4.0.so.18)
                                             #17 0x00007fb2b981743a g_main_context_dispatch (libglib-2.0.so.0)
                                             #18 0x00007fb2b98177f0 n/a (libglib-2.0.so.0)
                                             #19 0x00007fb2b9817b12 g_main_loop_run (libglib-2.0.so.0)
                                             #20 0x00007fb2b93d9b10 _ZN3WTF7RunLoop3runEv (libjavascriptcoregtk-4.0.so.18)
                                             #21 0x00007fb2bc41adda n/a (libwebkit2gtk-4.0.so.37)
                                             #22 0x00007fb2bb8bb291 __libc_start_main (libc.so.6)
                                             #23 0x000000000040075a _start (WebKitWebProcess)

                                             Stack trace of thread 1927:
                                             #0  0x00007fb2bb97a48d poll (libc.so.6)
                                             #1  0x00007fb2b9817786 n/a (libglib-2.0.so.0)
                                             #2  0x00007fb2b9817b12 g_main_loop_run (libglib-2.0.so.0)
                                             #3  0x00007fb2b93d9b10 _ZN3WTF7RunLoop3runEv (libjavascriptcoregtk-4.0.so.18)
                                             #4  0x00007fb2b93d8732 n/a (libjavascriptcoregtk-4.0.so.18)
                                             #5  0x00007fb2b93a3d75 n/a (libjavascriptcoregtk-4.0.so.18)
                                             #6  0x00007fb2b93d6aea n/a (libjavascriptcoregtk-4.0.so.18)
                                             #7  0x00007fb2b7e26454 start_thread (libpthread.so.0)
                                             #8  0x00007fb2bb9837df __clone (libc.so.6)

                                             Stack trace of thread 1929:
                                             #0  0x00007fb2bb97a48d poll (libc.so.6)
                                             #1  0x00007fb2b9817786 n/a (libglib-2.0.so.0)
                                             #2  0x00007fb2b9817b12 g_main_loop_run (libglib-2.0.so.0)
                                             #3  0x00007fb2b93d9b10 _ZN3WTF7RunLoop3runEv (libjavascriptcoregtk-4.0.so.18)
                                             #4  0x00007fb2b93d8732 n/a (libjavascriptcoregtk-4.0.so.18)
                                             #5  0x00007fb2b93a3d75 n/a (libjavascriptcoregtk-4.0.so.18)
                                             #6  0x00007fb2b93d6aea n/a (libjavascriptcoregtk-4.0.so.18)
                                             #7  0x00007fb2b7e26454 start_thread (libpthread.so.0)
                                             #8  0x00007fb2bb9837df __clone (libc.so.6)

                                             Stack trace of thread 1928:
                                             #0  0x00007fb2bb97a48d poll (libc.so.6)
                                             #1  0x00007fb2b9817786 n/a (libglib-2.0.so.0)
                                             #2  0x00007fb2b9817b12 g_main_loop_run (libglib-2.0.so.0)
                                             #3  0x00007fb2b93d9b10 _ZN3WTF7RunLoop3runEv (libjavascriptcoregtk-4.0.so.18)
                                             #4  0x00007fb2b93d8732 n/a (libjavascriptcoregtk-4.0.so.18)
                                             #5  0x00007fb2b93a3d75 n/a (libjavascriptcoregtk-4.0.so.18)
                                             #6  0x00007fb2b93d6aea n/a (libjavascriptcoregtk-4.0.so.18)
                                             #7  0x00007fb2b7e26454 start_thread (libpthread.so.0)
                                             #8  0x00007fb2bb9837df __clone (libc.so.6)

                                             Stack trace of thread 1926:
                                             #0  0x00007fb2bb952ffd __nanosleep (libc.so.6)
                                             #1  0x00007fb2b93def34 _ZN7bmalloc4Heap8scavengeERSt11unique_lockINS_11StaticMutexEENSt6chrono8durationIlSt
                                             #2  0x00007fb2b93df08f _ZN7bmalloc4Heap18concurrentScavengeEv (libjavascriptcoregtk-4.0.so.18)
                                             #3  0x00007fb2b93e036e _ZN7bmalloc9AsyncTaskINS_4HeapEMS1_FvvEE13threadRunLoopEv (libjavascriptcoregtk-4.0.
                                             #4  0x00007fb2b93e0549 _ZN7bmalloc9AsyncTaskINS_4HeapEMS1_FvvEE16threadEntryPointEPS4_ (libjavascriptcoregt
                                             #5  0x00007fb2b28b931f execute_native_thread_routine (libstdc++.so.6)
                                             #6  0x00007fb2b7e26454 start_thread (libpthread.so.0)
                                             #7  0x00007fb2bb9837df __clone (libc.so.6)
```

I've tried to use the provided package, but I don't have the dependency, and I cannot see it in the AUR either:

```
:: The following package cannot be upgraded due to unresolvable dependencies:
      lightdm-webkit2-greeter-next
```

**Comment by lots0logs** [comment]
@jonathanio Oh yeah, I forgot about the wallpapers dep. You can simply reinstall the AUR package, just edit the PKGBUILD and make these changes:

In the source array, change the end of the first URL as follows:

`/archive/${pkgver}.zip` -> `/archive/master.zip`

Also bump the `pkgrel` by 1.

**Comment by lots0logs** [comment]
@mrmodolo Have you configured your avatar as described [here](https://wiki.archlinux.org/index.php/LightDM#Changing_your_avatar)?

**Comment by mrmodolo** [comment]
Hi!
The icons always worked, I believe that after some update this behavior started to happen.

The instructions at https://wiki.archlinux.org/index.php/LightDM#Changing_your_avatar are not required in the installation of Antergos since it sets up during the installation the accountsservice package.

Even so, I checked and the package accountsservice is installed and the path is correctly indicated in /var/lib/AccountService/users/ modolo with the line:
Icon=/usr/share/pixmaps/faces/guitar.jpg.

If I inspect the avatar element on the login screen I see the correct path:

`<img src="/usr/share/pixmaps/faces/guitar.jpg" class="img-circle" alt="Marcelo Módolo"> = $0`

**Comment by mrmodolo** [comment]
I also checked the permissions ...

**Comment by mrmodolo** [comment]
I believe the problem is related to the image path. I have already verified that it is not permission. I also checked that if I change the src attribute of the avatar to any image in "/usr/share/lightdm-webkit/themes/antergos/img/" it appears instantly!

**Comment by timycyip** [comment]
Thanks mrmodolo! My avatar appears and the error has gone after modifying the user_image pointing to the avatar folder.

**Comment by mrmodolo** [comment]
Hi!

How can I download the package with the fix?

Thanks,
Marcelo

**Comment by mrmodolo** [comment]
Hi!
I read the instructions to compile the source code!
meson ... ninja ... sudo ninja install
Everything working now! I can already see the avatar!

Thanks!

**Comment by undermycloud** [comment]
And after that we wonder why regular people are not using linux

**Comment by lots0logs** [comment]
@undermycloud I don't understand what point you are trying to make here. There are precompiled packages available for all major linux distributions. If you are having trouble then please open an issue here on github with the details so that we can look into it. Thanks.
